quarkus.container-image.group=epf
quarkus.container-image.name=epf-file
quarkus.kubernetes.name=epf-file
quarkus.http.port=9194
quarkus.jib.ports=9194
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9194
quarkus.kubernetes.ports."http".host-port=9194
quarkus.s3.path-style-access=true
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=default
quarkus.s3.endpoint-override=http://localhost:9000
quarkus.s3."public_client".endpoint-override=https://suitably-useful-arachnid.ngrok-free.app
quarkus.kubernetes.env.vars.QUARKUS_S3_ENDPOINT_OVERRIDE=http://rustfs-svc:9000
quarkus.kubernetes.env.mapping.AWS_ACCESS_KEY_ID.from-secret=rustfs
quarkus.kubernetes.env.mapping.AWS_ACCESS_KEY_ID.with-key=RUSTFS_ACCESS_KEY
quarkus.kubernetes.env.mapping.AWS_SECRET_ACCESS_KEY.from-secret=rustfs
quarkus.kubernetes.env.mapping.AWS_SECRET_ACCESS_KEY.with-key=RUSTFS_SECRET_KEY
quarkus.kubernetes.resources.requests.cpu=15m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.kubernetes.env.vars.QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.helm.name=epf-file