quarkus.container-image.group=epf
quarkus.container-image.name=chrome-devtools-mcp
quarkus.kubernetes.name=chrome-devtools-mcp
quarkus.http.port=8000
quarkus.jib.ports=8000
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=8000
quarkus.kubernetes.ports."http".host-port=8000
quarkus.kubernetes.resources.requests.cpu=25m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.helm.name=chrome-devtools-mcp