ALTER DATABASE odoo WITH is_template TRUE;
CREATE DATABASE odoo_template WITH OWNER = "odoo.odoo" TEMPLATE = odoo ENCODING = 'UTF8' LOCALE_PROVIDER = 'libc' TABLESPACE = pg_default CONNECTION LIMIT = -1 IS_TEMPLATE = True;
ALTER DATABASE odoo WITH is_template FALSE;
CREATE DATABASE odoo1 WITH OWNER = "odoo.odoo" TEMPLATE = odoo_template ENCODING = 'UTF8' LOCALE_PROVIDER = 'libc' TABLESPACE = pg_default CONNECTION LIMIT = -1 IS_TEMPLATE = False;