/*Basic Roles BEGIN*/
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO analyst1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO any_role1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO architect1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO developer1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO project_manager1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO stakeholder1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO tester1;
/*Basic Roles END*/

/*Deployment BEGIN*/
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO course_developer1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO deployment_engineer1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO deployment_manager1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO product_owner1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO technical_writer1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO trainer1;
/*Deployment END*/

/*Environment BEGIN*/
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO process_engineer1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO tool_specialist1;
/*Environment END*/

/*Basic Roles BEGIN*/
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO analyst1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO any_role1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO architect1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO developer1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO project_manager1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO stakeholder1;
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO tester1;
/*Basic Roles END*/