/*Basic Roles BEGIN*/
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO analyst1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO any_role1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO architect1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO developer1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO project_manager1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO stakeholder1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO tester1;
/*Basic Roles END*/

/*Deployment BEGIN*/
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO course_developer1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO deployment_engineer1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO deployment_manager1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO product_owner1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO technical_writer1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO trainer1;
/*Deployment END*/

/*Environment BEGIN*/
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO process_engineer1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO tool_specialist1;
/*Environment END*/

/*Basic Roles BEGIN*/
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO analyst1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO any_role1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO architect1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO developer1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO project_manager1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO stakeholder1;
GRANT ALL PRIVILEGES ON SCHEMA INFORMATION_SCHEMA TO tester1;
/*Basic Roles END*/