/*Basic Roles BEGIN*/
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "analyst1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "any_role1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "architect1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "developer1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "project_manager1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "stakeholder1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "tester1@openup";
/*Basic Roles END*/

/*Deployment BEGIN*/
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "course_developer1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "deployment_engineer1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "deployment_manager1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "product_owner1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "technical_writer1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "trainer1@openup";
/*Deployment END*/

/*Environment BEGIN*/
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "process_engineer1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "tool_specialist1@openup";
/*Environment END*/

/*Basic Roles BEGIN*/
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "analyst1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "any_role1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "architect1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "developer1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "project_manager1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "stakeholder1@openup";
GRANT SELECT, UPDATE ON SCHEMA EPF_SECURITY TO "tester1@openup";
/*Basic Roles END*/