mp.jwt.verify.issuer=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev
mp.jwt.verify.publickey.location=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev/protocol/openid-connect/certs
epf.management.organization.domain=localhost
epf.management.persistence.template=epf_template
epf.management.auth.client.id=admin-cli
epf.management.auth.client.secret=DnHAGTmZbJejvMBYLl5PyZFGPcuApPoN