SELECT GRANTEDROLE FROM INFORMATION_SCHEMA.RIGHTS WHERE GRANTEDROLE <> '' AND GRANTEETYPE = 'ROLE' AND GRANTEE IN
(
    SELECT GRANTEDROLE FROM INFORMATION_SCHEMA.RIGHTS WHERE GRANTEETYPE = 'USER' AND GRANTEE = ?
)
UNION 
    SELECT GRANTEDROLE FROM INFORMATION_SCHEMA.RIGHTS WHERE GRANTEDROLE <> '' AND GRANTEETYPE = 'USER' AND GRANTEE = ?;
SELECT * FROM FT_SEARCH_DATA(?, ?, ?);