/*Basic Roles BEGIN*/
CREATE ROLE IF NOT EXISTS Analyst;
CREATE ROLE IF NOT EXISTS Any_Role;
CREATE ROLE IF NOT EXISTS Architect;
CREATE ROLE IF NOT EXISTS Developer;
CREATE ROLE IF NOT EXISTS Project_Manager;
CREATE ROLE IF NOT EXISTS Stakeholder;
CREATE ROLE IF NOT EXISTS Tester;
/*Basic Roles END*/

/*Deployment BEGIN*/
CREATE ROLE IF NOT EXISTS Course_Developer;
CREATE ROLE IF NOT EXISTS Deployment_Engineer;
CREATE ROLE IF NOT EXISTS Deployment_Manager;
CREATE ROLE IF NOT EXISTS Product_Owner;
CREATE ROLE IF NOT EXISTS Technical_Writer;
CREATE ROLE IF NOT EXISTS Trainer;
/*Deployment END*/

/*Environment BEGIN*/
CREATE ROLE IF NOT EXISTS Process_Engineer;
CREATE ROLE IF NOT EXISTS Tool_Specialist;
/*Environment END*/