---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: epf-gateway
    app.kubernetes.io/version: 1.0.0
  name: epf-gateway
spec:
  ports:
    - name: https
      port: 8443
      targetPort: 8443
  selector:
    app.kubernetes.io/name: epf-gateway
    app.kubernetes.io/version: 1.0.0
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: epf-gateway
    app.kubernetes.io/version: 1.0.0
  name: epf-gateway-internal
spec:
  ports:
    - name: debug
      port: 5006
      targetPort: 5006
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: epf-gateway
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: epf-gateway
  name: epf-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: epf-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: epf-gateway
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HAZELCAST_KUBERNETES_SERVICE_DNS
              value: hazelcast.default.svc.cluster.local
          image: epf/epf-gateway:1.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: epf-gateway
          ports:
            - containerPort: 5006
              name: debug
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
