quarkus.index-dependency.jackson-databind.group-id=com.fasterxml.jackson.core
quarkus.index-dependency.jackson-databind.artifact-id=jackson-databind
quarkus.index-dependency.jsonschema-generator.group-id=com.github.victools
quarkus.index-dependency.jsonschema-generator.artifact-id=jsonschema-generator
quarkus.index-dependency.jsonschema-module-jackson.group-id=com.github.victools
quarkus.index-dependency.jsonschema-module-jackson.artifact-id=jsonschema-module-jackson
quarkus.container-image.group=epf
quarkus.container-image.name=epf-mcp-gateway
quarkus.kubernetes.name=epf-mcp-gateway
quarkus.http.port=9197
quarkus.jib.ports=9197
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9197
quarkus.kubernetes.ports."http".host-port=9197
quarkus.kubernetes.resources.requests.cpu=25m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.helm.name=epf-mcp-gateway
quarkus.rest-client.epf-query.url=http://localhost:9188
quarkus.rest-client.epf-schema.url=http://localhost:9188
quarkus.rest-client.epf-persistence.url=http://localhost:9181
quarkus.kubernetes.env.vars.QUARKUS_REST_CLIENT_EPF_QUERY_URL=http://epf-query:9188
quarkus.kubernetes.env.vars.QUARKUS_REST_CLIENT_EPF_SCHEMA_URL=http://epf-query:9188
quarkus.kubernetes.env.vars.QUARKUS_REST_CLIENT_EPF_PERSISTENCE_URL=http://epf-persistence:9181
quarkus.kubernetes.env.vars.QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
quarkus.kubernetes.env.vars.QUARKUS_OIDC_AUTH_SERVER_URL=http://keycloak:8080/auth/realms/EPF-dev
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.mcp.server."persistence".http.root-path=/persistence/mcp
quarkus.mcp.server."query".http.root-path=/query/mcp
quarkus.http.auth.permission.authenticated.paths=/mcp/*,/persistence/mcp/*,/query/mcp/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.oidc.auth-server-url=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev