quarkus.container-image.group=epf
quarkus.container-image.name=epf-mcp-gateway
quarkus.kubernetes.name=epf-mcp-gateway
quarkus.http.port=9197
quarkus.jib.ports=9197
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9197
quarkus.kubernetes.ports."http".host-port=9197
quarkus.kubernetes.resources.requests.cpu=25m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.helm.name=epf-mcp-gateway
quarkus.rest-client.epf-query.url=http://localhost:9188
quarkus.kubernetes.env.vars.QUARKUS_REST_CLIENT_EPF_QUERY_URL=http://epf-query.default.svc.cluster.local:9188
quarkus.http.auth.permission.authenticated.paths=/mcp/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.oidc.auth-server-url=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev