quarkus.container-image.group=epf
quarkus.container-image.name=epf-agent-webapp
quarkus.kubernetes.name=epf-agent-webapp
quarkus.http.port=3000
quarkus.jib.ports=3000
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=3000
quarkus.kubernetes.ports."http".host-port=3000
quarkus.kubernetes.resources.requests.cpu=25m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.kubernetes.startup-probe.http-action-path=/api/health
quarkus.kubernetes.startup-probe.initial-delay=30S
quarkus.kubernetes.liveness-probe.http-action-path=/api/health
quarkus.kubernetes.liveness-probe.initial-delay=30s
quarkus.kubernetes.readiness-probe.http-action-path=/api/health
quarkus.kubernetes.readiness-probe.initial-delay=30s
quarkus.helm.name=epf-agent-webapp
quarkus.kubernetes.env.mapping.CLIENT_ID.from-secret=oidc
quarkus.kubernetes.env.mapping.CLIENT_ID.with-key=OIDC_CLIENT_ID
quarkus.kubernetes.env.mapping.CLIENT_SECRET.from-secret=oidc
quarkus.kubernetes.env.mapping.CLIENT_SECRET.with-key=OIDC_CLIENT_SECRET
quarkus.kubernetes.env.vars.ISSUER=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev
#quarkus.kubernetes.env.vars.NEXTAUTH_URL=https://touching-pika-enabled.ngrok-free.app
quarkus.kubernetes.env.vars.NEXTAUTH_URL=http://localhost
quarkus.kubernetes.env.vars.AUTH_REQUEST_TIMEOUT=10000
quarkus.kubernetes.env.vars.JWT_MAX_AGE=300
quarkus.kubernetes.env.mapping.NEXTAUTH_SECRET.from-secret=nextauth
quarkus.kubernetes.env.mapping.NEXTAUTH_SECRET.with-key=NEXTAUTH_SECRET
quarkus.kubernetes.env.vars.EPF_AGENT_URL=http://epf-agent:8123
quarkus.kubernetes.env.vars.DEBUG=true
quarkus.kubernetes.ingress.expose=true
quarkus.kubernetes.ingress.ingress-class-name=haproxy
#quarkus.kubernetes.ingress.host=touching-pika-enabled.ngrok-free.app
quarkus.kubernetes.ingress.host=localhost