---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: epf-auth
    app.kubernetes.io/version: 1.0.0
  name: epf-auth
spec:
  ports:
    - name: http
      port: 9196
      protocol: TCP
      targetPort: 9196
  selector:
    app.kubernetes.io/name: epf-auth
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: epf-auth
    app.kubernetes.io/version: 1.0.0
  name: epf-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: epf-auth
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: epf-auth
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/library/epf-auth:1.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/live
              port: 9196
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: epf-auth
          ports:
            - containerPort: 9196
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/ready
              port: 9196
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/started
              port: 9196
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
