package epf.workflow.schema;

import java.io.Serializable;
import org.eclipse.jnosql.mapping.Embeddable;
import org.eclipse.microprofile.graphql.Description;
import epf.workflow.schema.util.StringOrInteger;
import jakarta.nosql.Column;

@Embeddable
public class ErrorThrowDefinition implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column
	@Description("The name of the error definition to throw. If set, all other properties are ignored.")
	private String refName;
	
	@Column
	@Description("The URI reference that identifies the type of error to throw. Supports runtime expressions.")
	private String type;

	@Column
	@Description("The status code generated by the origin for an occurrence of a problem. Supports runtime expressions.")
	private StringOrInteger status;
	
	@Column
	@Description("A short, human-readable summary of a problem type. Supports runtime expressions.")
	private String title;
	
	@Column
	@Description("A human-readable explanation specific to an occurrence of a problem. Supports runtime expressions.")
	private String detail;

	public String getRefName() {
		return refName;
	}

	public void setRefName(String refName) {
		this.refName = refName;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public StringOrInteger getStatus() {
		return status;
	}

	public void setStatus(StringOrInteger status) {
		this.status = status;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}
}
