quarkus.index-dependency.cache-api.group-id=javax.cache
quarkus.index-dependency.cache-api.artifact-id=cache-api
quarkus.index-dependency.hazelcast.group-id=com.hazelcast
quarkus.index-dependency.hazelcast.artifact-id=hazelcast
quarkus.container-image.group=epf
quarkus.container-image.name=epf-cache
quarkus.kubernetes.name=epf-cache
quarkus.http.port=9187
quarkus.jib.ports=9187
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9187
quarkus.kubernetes.ports."http".host-port=9187
quarkus.kubernetes.resources.requests.cpu=25m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.kubernetes.env.vars.HAZELCAST_KUBERNETES_SERVICE_DNS=hazelcast
quarkus.kubernetes.env.vars.QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-collector:4317
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.helm.name=epf-cache