quarkus.container-image.group=epf
quarkus.container-image.name=epf-agent
quarkus.kubernetes.name=epf-agent
quarkus.http.port=8123
quarkus.jib.ports=8123
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=8123
quarkus.kubernetes.ports."http".host-port=8123
quarkus.kubernetes.resources.requests.cpu=15m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=250m
quarkus.kubernetes.resources.limits.memory=256Mi
quarkus.kubernetes.startup-probe.http-action-path=/health
quarkus.kubernetes.startup-probe.initial-delay=60S
quarkus.kubernetes.liveness-probe.http-action-path=/health
quarkus.kubernetes.liveness-probe.initial-delay=60s
quarkus.kubernetes.readiness-probe.http-action-path=/health
quarkus.kubernetes.readiness-probe.initial-delay=60s
quarkus.helm.name=epf-agent
quarkus.kubernetes.env.mapping.OPENAI_API_KEY.from-secret=vllm
quarkus.kubernetes.env.mapping.OPENAI_API_KEY.with-key=VLLM_API_KEY
quarkus.kubernetes.env.mapping.REDIS_PASSWORD.from-secret=redis
quarkus.kubernetes.env.mapping.REDIS_PASSWORD.with-key=redis-password
quarkus.kubernetes.env.fields.pod-name=metadata.name
quarkus.kubernetes.env.vars.OPENAI_MODEL=TevunahAi/Granite-3.3-8B-Instruct-GPTQ
quarkus.kubernetes.env.vars.OPENAI_BASE_URL=http://vllm:8000/v1
quarkus.kubernetes.env.vars.MCP_SERVER_URL=http://epf-mcp-gateway:9197/mcp
quarkus.kubernetes.env.vars.MCP_SERVER_URL_FORMAT=http://epf-mcp-gateway:9197/{}/mcp
quarkus.kubernetes.env.vars.CHROME_DEVTOOLS_MCP_SERVER_URL=http://chrome-devtools-mcp:8000/mcp
quarkus.kubernetes.env.vars.JWT_KEY_URL=http://keycloak:8080/auth/realms/EPF-dev/protocol/openid-connect/certs
quarkus.kubernetes.env.vars.JWT_ISSUER=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev
quarkus.kubernetes.env.vars.MODEL_CALL_THREAD_LIMIT=10
quarkus.kubernetes.env.vars.MODEL_CALL_RUN_LIMIT=5
quarkus.kubernetes.env.vars.TOOL_CALL_THREAD_LIMIT=10
quarkus.kubernetes.env.vars.TOOL_CALL_RUN_LIMIT=5
quarkus.kubernetes.env.vars.DEBUG=true
quarkus.kubernetes.env.vars.CHECKPOINTER_PERSISTENCE_URL_FORMAT=redis://redis-master:6379
quarkus.kubernetes.env.vars.STORE_PERSISTENCE_URL_FORMAT=redis://:{}@redis-master:6379
quarkus.kubernetes.env.vars.CACHE_PERSISTENCE_URL_FORMAT=redis://redis-master:6379
quarkus.kubernetes.env.vars.REDIS_HOST=redis-master
quarkus.kubernetes.env.vars.OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
quarkus.kubernetes.env.vars.OTEL_SERVICE_NAME=EPF-agent
quarkus.kubernetes.env.vars.OTEL_EXPORTER_OTLP_PROTOCOL=grpc
quarkus.kubernetes.env.vars.OTEL_EXPORTER_OTLP_INSECURE=true