package epf.workflow.schema;

import java.net.URI;
import org.eclipse.microprofile.graphql.Description;
import jakarta.validation.constraints.NotNull;

@Description("Defines the Problem Details RFC compliant description of an error.")
public class Error {

	@NotNull
	@Description("A URI reference that identifies the error type. For cross-compatibility concerns, it is strongly recommended to use Standard Error Types whenever possible.")
	private URI type;
	
	@NotNull
	@Description("The status code generated by the origin for this occurrence of the error. For cross-compatibility concerns, it is strongly recommended to use HTTP Status Codes whenever possible.")
	private Integer status;
	
	@Description("A JSON Pointer used to reference the component the error originates from.")
	private String instance;
	
	@Description("A short, human-readable summary of the error.")
	private String title;
	
	@Description("A human-readable explanation specific to this occurrence of the error.")
	private String detail;

	public URI getType() {
		return type;
	}

	public void setType(URI type) {
		this.type = type;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getInstance() {
		return instance;
	}

	public void setInstance(String instance) {
		this.instance = instance;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}
}
