quarkus.index-dependency.EPF-json-schema.group-id=openup
quarkus.index-dependency.EPF-json-schema.artifact-id=EPF-json-schema
quarkus.http.port=9191
quarkus.jib.ports=9191
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9191
quarkus.kubernetes.ports."http".host-port=9191
quarkus.container-image.group=epf
quarkus.container-image.name=epf-workflow-management
quarkus.kubernetes.resources.requests.cpu=15m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.kubernetes.name=epf-workflow-management
quarkus.mongodb.database=epf_workflow_management
quarkus.mongodb.hosts=localhost:27017
quarkus.kubernetes.env.vars.QUARKUS_MONGODB_HOSTS=mongodb-headless:27017
quarkus.kubernetes.env.vars.QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.helm.name=epf-workflow-management