set epf_gateway_url=https://localhost:9543/gateway/
set epf_webapp_url=https://localhost/webapp/
set epf_client_net_ssl_keyStore=C://GIT/JavaEE/OpenUP/dev.p12
set epf_client_net_ssl_keyStoreType=PKCS12
set epf_client_net_ssl_keyStorePassword=changeit
set epf_client_net_ssl_trustStore=C://GIT/JavaEE/OpenUP/dev.p12
set epf_client_net_ssl_trustStoreType=PKCS12
set epf_client_net_ssl_trustStorePassword=changeit
set epf_security_jwt_verify_publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo1gB2pJN6RTgqIiYTAYZdlQ/NeyCC6t45H/GfeVqEu3vMWQkO/ywDH6QZByf3FvaWNc9/+2tgE5dOhU3wpIx+C9kSaQc9n7x57QGzZwQ3H1MkzrDLf3jI4XHwhtle2EJ9pofERrVs5UF2yuqDWPvFNiijOzN2GMFChCwoK7fwkMweBfrDEs3gbtMG1dyoUKYOxLckCb5xmy7+jSI74lsP3kcP7LidkJr0jaKiJSFVuAfJ0FQ7Gc15VVi2lyP+KiO6p165tdau7jv1G+KJbJPtBdLLCXcxRq5Yq9VQVybykN+7nbQisqlqe6RmVPr3qZHue7nnxPagNJ7gVbEtnmGzwIDAQAB
call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"