call ./shutdownc.bat
call ./clean.bat
call ./startupc.bat
call ./compile.bat
cd EPF-config
call ./dev.bat
cd ../
cd EPF-messaging
call ./dev.bat
cd ../
cd EPF-logging
call ./dev.bat
cd ../
cd EPF-cache
call ./dev.bat
cd ../
cd EPF-transaction-internal
call ./dev.bat
cd ../
cd EPF-transaction
call ./dev.bat
cd ../
cd EPF-persistence
call ./dev.bat
cd ../
cd EPF-net
call ./dev.bat
cd ../
cd EPF-gateway
call ./dev.bat
cd ../
call ./webapp_deploy.bat
cd EPF-shell
call ./dev.bat
cd ../
cd EPF-tests
call ./test.bat