---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.0.0
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: jaegertracing/all-in-one
          imagePullPolicy: IfNotPresent
          name: jaeger
          ports:
            - containerPort: 5775
              name: port1
              protocol: UDP
            - containerPort: 6831
              name: port2
              protocol: UDP
            - containerPort: 6832
              name: port3
              protocol: UDP
            - containerPort: 5778
              name: port4
              protocol: TCP
            - containerPort: 16686
              name: http
              protocol: TCP
            - containerPort: 14268
              name: port5
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.0.0
  name: jaeger
spec:
  ports:
    - name: port1
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: port2
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: port3
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: port4
      port: 5778
      protocol: TCP
      targetPort: 5778
    - name: http
      port: 16686
      protocol: TCP
      targetPort: 16686
    - name: port5
      port: 14268
      protocol: TCP
      targetPort: 14268
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
