---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-volume
  labels:
    type: local
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 1.0.0
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/c/postgresql_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-claim
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 1.0.0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 1.0.0
  name: postgresql
spec:
  ports:
    - name: http
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 1.0.0
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/version: 1.0.0
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', "chown -R 1001:1001 /bitnami/postgresql"]
          volumeMounts:
            - mountPath: "/bitnami/postgresql"
              name: postgresql-data
              readOnly: false
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POSTGRESQL_USERNAME
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: "090323508"
            - name: POSTGRESQL_DATABASE
              value: epf
          image: bitnami/postgresql
          imagePullPolicy: IfNotPresent
          name: postgresql
          ports:
            - containerPort: 5432
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: "/bitnami/postgresql"
              name: postgresql-data
              readOnly: false
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-claim
            readOnly: false