---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/version: 1.0.0
  name: zookeeper
spec:
  ports:
    - name: http
      port: 2181
      targetPort: 2181
  selector:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/version: 1.0.0
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zookeeper
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          image: bitnami/zookeeper
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
            - containerPort: 2181
              name: http
              protocol: TCP
