---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: supavisor-tls
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: supavisor-tls
  namespace: default
spec:
  ca:
    secretName: supavisor-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: supavisor-tls
  namespace: default
spec:
  isCA: true
  commonName: osm-system
  secretName: supavisor-tls
  issuerRef:
    name: supavisor-tls
    kind: ClusterIssuer
    group: cert-manager.io