quarkus.index-dependency.EPF-json-schema.group-id=openup
quarkus.index-dependency.EPF-json-schema.artifact-id=EPF-json-schema
quarkus.container-image.group=epf
quarkus.container-image.name=epf-workflow
quarkus.kubernetes.name=epf-workflow
quarkus.http.port=9189
quarkus.jib.ports=9189
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9189
quarkus.kubernetes.ports."http".host-port=9189
quarkus.kubernetes.resources.requests.cpu=25m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.kubernetes.env.vars.mp-messaging-connector-smallrye-kafka-security-protocol=SASL_PLAINTEXT
quarkus.kubernetes.env.vars.mp-messaging-connector-smallrye-kafka-sasl-mechanism=SCRAM-SHA-256
quarkus.kubernetes.env.mapping.mp-messaging-connector-smallrye-kafka-sasl-jaas-config.from-secret=kafka
quarkus.kubernetes.env.mapping.mp-messaging-connector-smallrye-kafka-sasl-jaas-config.with-key=jaas
quarkus.kubernetes.env.vars.mp-messaging-connector-smallrye-kafka-bootstrap-servers=kafka-controller-0.kafka-controller-headless:9092
quarkus.kubernetes.env.vars.quarkus-lra-coordinator-url=http://epf-transaction:50000/lra-coordinator
quarkus.kubernetes.env.vars.HAZELCAST_KUBERNETES_SERVICE_DNS=hazelcast
quarkus.mongodb.database=epf_workflow_management
quarkus.mongodb.hosts=localhost:27017
quarkus.cassandra.local-datacenter=datacenter1
quarkus.kubernetes.env.vars.QUARKUS_MONGODB_HOSTS=mongodb-headless:27017
quarkus.kubernetes.env.vars.JNOSQL_CASSANDRA_HOST=scylladb
quarkus.kubernetes.env.vars.QUARKUS_CASSANDRA_CONTACT_POINTS=scylladb:9042
quarkus.kubernetes.env.vars.QUARKUS_CASSANDRA_LOCAL_DATACENTER=datacenter1
quarkus.kubernetes.env.vars.epf-concurrent-url=ws://epf-concurrent:9193/synchronized/
quarkus.kubernetes.env.vars.QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.helm.name=epf-workflow
jnosql.column.database=epf-workflow
jnosql.document.database=epf-workflow