CREATE ALIAS IF NOT EXISTS FTL_INIT FOR "org.h2.fulltext.FullTextLucene.init";
CALL FTL_INIT();

CALL FTL_CREATE_INDEX('EPF_DELIVERY_PROCESSES', 'DELIVERY_PROCESS', NULL);
CALL FTL_CREATE_INDEX('EPF_DELIVERY_PROCESSES', 'PHASE', NULL);
CALL FTL_CREATE_INDEX('EPF_DELIVERY_PROCESSES', 'CAPABILITY_PATTERN', NULL);
CALL FTL_CREATE_INDEX('EPF_DELIVERY_PROCESSES', 'ACTIVITY', NULL);
CALL FTL_CREATE_INDEX('EPF_DELIVERY_PROCESSES', 'ITERATION', NULL);
CALL FTL_CREATE_INDEX('EPF_DELIVERY_PROCESSES', 'MILESTONE', NULL);

CALL FTL_CREATE_INDEX('EPF_ROLES', 'ROLE_SET', NULL);
CALL FTL_CREATE_INDEX('EPF_ROLES', 'EPF_ROLE', NULL);
CALL FTL_CREATE_INDEX('EPF_ROLES', 'ROLES', NULL);

CALL FTL_CREATE_INDEX('EPF_WORK_PRODUCTS', 'EPF_DOMAIN', NULL);
CALL FTL_CREATE_INDEX('EPF_WORK_PRODUCTS', 'ARTIFACT', NULL);
CALL FTL_CREATE_INDEX('EPF_WORK_PRODUCTS', 'DELIVERABLE', NULL);
CALL FTL_CREATE_INDEX('EPF_WORK_PRODUCTS', 'WORK_PRODUCTS', NULL);
CALL FTL_CREATE_INDEX('EPF_WORK_PRODUCTS', 'WORK_PRODUCT_SLOT', NULL);
CALL FTL_CREATE_INDEX('EPF_WORK_PRODUCTS', 'ROLE_MODIFIES', NULL);
CALL FTL_CREATE_INDEX('EPF_WORK_PRODUCTS', 'ARTIFACT_FULFILLED_SLOTS', NULL);

CALL FTL_CREATE_INDEX('EPF_TASKS', 'DISCIPLINE', NULL);
CALL FTL_CREATE_INDEX('EPF_TASKS', 'TASK', NULL);
CALL FTL_CREATE_INDEX('EPF_TASKS', 'TASKS', NULL);
CALL FTL_CREATE_INDEX('EPF_TASKS', 'ROLE_ADDITIONALLY_PERFORMS', NULL);
CALL FTL_CREATE_INDEX('EPF_TASKS', 'TASK_INPUTS_MANDATORY', NULL);
CALL FTL_CREATE_INDEX('EPF_TASKS', 'TASK_INPUTS_OPTIONAL', NULL);
CALL FTL_CREATE_INDEX('EPF_TASKS', 'TASK_OUTPUTS', NULL);
