quarkus.container-image.image=ghcr.io/supabase/supavisor:2.9.7
quarkus.kubernetes.name=supavisor
quarkus.http.port=4000
quarkus.jib.ports=4000,5432,6543
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=4000
quarkus.kubernetes.ports."http".host-port=4000
quarkus.kubernetes.ports."session".container-port=5432
quarkus.kubernetes.ports."session".host-port=5432
quarkus.kubernetes.ports."transaction".container-port=6543
quarkus.kubernetes.ports."transaction".host-port=6543
quarkus.kubernetes.env.vars.PORT=4000
quarkus.kubernetes.env.vars.PROXY_PORT_SESSION=5432
quarkus.kubernetes.env.vars.PROXY_PORT_TRANSACTION=6543
quarkus.kubernetes.env.vars.DATABASE_URL=ecto://postgres:090323508@postgresql-primary:5432/postgres
quarkus.kubernetes.env.vars.CLUSTER_POSTGRES=false
quarkus.kubernetes.env.vars.GLOBAL_DOWNSTREAM_CERT_PATH=/supavisor-tls/tls.crt
quarkus.kubernetes.env.vars.GLOBAL_DOWNSTREAM_KEY_PATH=/supavisor-tls/tls.key
quarkus.kubernetes.env.vars.NAMED_PREPARED_STATEMENTS_ENABLED=true
quarkus.kubernetes.env.mapping.SECRET_KEY_BASE.from-secret=supavisor
quarkus.kubernetes.env.mapping.SECRET_KEY_BASE.with-key=SECRET_KEY_BASE
quarkus.kubernetes.env.mapping.VAULT_ENC_KEY.from-secret=supavisor
quarkus.kubernetes.env.mapping.VAULT_ENC_KEY.with-key=VAULT_ENC_KEY
quarkus.kubernetes.env.mapping.API_JWT_SECRET.from-secret=supavisor
quarkus.kubernetes.env.mapping.API_JWT_SECRET.with-key=API_JWT_SECRET
quarkus.kubernetes.env.mapping.METRICS_JWT_SECRET.from-secret=supavisor
quarkus.kubernetes.env.mapping.METRICS_JWT_SECRET.with-key=METRICS_JWT_SECRET
quarkus.kubernetes.env.vars.REGION=local
quarkus.kubernetes.env.vars.ERL_AFLAGS=-proto_dist inet_tcp
quarkus.kubernetes.command=/bin/sh,-c,/app/bin/migrate && /app/bin/server
quarkus.kubernetes.resources.requests.cpu=15m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=375m
quarkus.kubernetes.resources.limits.memory=384Mi
quarkus.kubernetes.secret-volumes.supavisor-tls.secret-name=supavisor-tls
quarkus.kubernetes.mounts.supavisor-tls.path=/supavisor-tls
#quarkus.kubernetes.readiness-probe.initial-delay=300S
quarkus.kubernetes.readiness-probe.tcp-socket-action=4000
#quarkus.kubernetes.liveness-probe.initial-delay=300S
quarkus.kubernetes.liveness-probe.tcp-socket-action=6543
quarkus.kubernetes.startup-probe.initial-delay=180S
quarkus.kubernetes.startup-probe.tcp-socket-action=4000
quarkus.helm.name=supavisor