package epf.workflow.schema.error;

import java.io.Serializable;
import jakarta.nosql.Embeddable;
import org.eclipse.microprofile.graphql.Description;
import jakarta.nosql.Column;
import jakarta.validation.constraints.NotNull;

@Embeddable
public class ErrorDefinition implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@NotNull
	@Column
	@Description("The name of the error. Must follow the Serverless Workflow Naming Convention")
	private String name;
	
	@Column
	@Description("An RFC 6901 JSON pointer that precisely identifies the component within a workflow definition (ex: funcRef, subflowRef, ...) from which the described error originates.")
	private String instance;
	
	@NotNull
	@Column
	@Description("An RFC 3986 URI reference that identifies the error type. The RFC 7807 Problem Details specification encourages that, when dereferenced, it provides human-readable documentation for the error type (e.g., using HTML). The specification strongly recommends using default error types for cross-compatibility concerns.")
	private String type;
	
	@NotNull
	@Column
	@Description("The status code generated by the origin for the occurrence of an error. Status codes are extensible by nature and runtimes are not required to understand the meaning of all defined status codes. However, for cross-compatibility concerns, the specification encourages using RFC 7231 HTTP Status Codes.")
	private String status;
	
	@Column
	@Description("A short, human-readable summary of an error type. It SHOULD NOT change from occurrence to occurrence of an error, except for purposes of localization.")
	private String title;
	
	@Column
	@Description("A human-readable explanation specific to the occurrence of an error.")
	private String detail;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getInstance() {
		return instance;
	}

	public void setInstance(String instance) {
		this.instance = instance;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
}
