quarkus.container-image.group=epf
quarkus.container-image.name=epf-search
quarkus.kubernetes.name=epf-search
quarkus.http.port=9198
quarkus.jib.ports=9198
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9198
quarkus.kubernetes.ports."http".host-port=9198
quarkus.kubernetes.resources.requests.cpu=15m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.kubernetes.startup-probe.http-action-path=/health
quarkus.kubernetes.liveness-probe.http-action-path=/health
quarkus.kubernetes.readiness-probe.http-action-path=/health
quarkus.kubernetes.env.mapping.OPENAI_API_KEY.from-secret=vllm
quarkus.kubernetes.env.mapping.OPENAI_API_KEY.with-key=VLLM_API_KEY
quarkus.kubernetes.env.vars.OPENAI_MODEL=TevunahAi/Granite-3.3-8B-Instruct-GPTQ
quarkus.kubernetes.env.vars.OPENAI_BASE_URL=http://vllm:8000/v1
quarkus.kubernetes.env.vars.JWT_KEY_URL=http://keycloak:8080/auth/realms/EPF-dev/protocol/openid-connect/certs
quarkus.kubernetes.env.vars.JWT_ISSUER=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev
quarkus.helm.name=epf-search
quarkus.kubernetes.env.vars.OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
quarkus.kubernetes.env.vars.OTEL_SERVICE_NAME=epf-search
quarkus.kubernetes.env.vars.OTEL_EXPORTER_OTLP_PROTOCOL=grpc
quarkus.kubernetes.env.vars.OTEL_EXPORTER_OTLP_INSECURE=true