apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-2404-container-disk
  namespace: default
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: ceph-block
  source:
    registry:
      url: docker://quay.io/capk/ubuntu-2404-container-disk:v1.34.1