<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
	<groupId>epf</groupId>
	<artifactId>EPF-parent-ext</artifactId>
	<version>1.0.0</version>
	<relativePath>../EPF-parent-ext/pom.xml</relativePath>
  </parent>
  <groupId>openup</groupId>
  <artifactId>EPF-mcp-gateway</artifactId>
  <name>Eclipse Process Framework MCP Gateway</name>
  <dependencies>
  	<dependency>
		<groupId>io.quarkus</groupId>
		<artifactId>quarkus-rest-client-jsonb</artifactId>
	</dependency>
	<dependency>
	    <groupId>io.quarkus</groupId>
	    <artifactId>quarkus-oidc</artifactId> 
	</dependency>
	<dependency>
		<groupId>io.quarkiverse.mcp</groupId>
		<artifactId>quarkus-mcp-server-http</artifactId>
	</dependency>
	<dependency>
	    <groupId>io.quarkiverse.mcp</groupId>
	    <artifactId>quarkus-mcp-server-hibernate-validator</artifactId>
	</dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
	   <groupId>io.quarkus</groupId>
	   <artifactId>quarkus-kubernetes</artifactId>
	</dependency>
	<dependency>
		<groupId>io.quarkus</groupId>
		<artifactId>quarkus-container-image-jib</artifactId>
	</dependency>
	<dependency>
		<groupId>io.quarkiverse.helm</groupId>
		<artifactId>quarkus-helm</artifactId>
	</dependency>
	<dependency>
	    <groupId>io.quarkus</groupId>
	    <artifactId>quarkus-opentelemetry</artifactId>
	</dependency>
	
	<dependency>
	    <groupId>com.github.jknack</groupId>
	    <artifactId>handlebars</artifactId>
	</dependency>
	<dependency>
	    <groupId>com.github.victools</groupId>
	    <artifactId>jsonschema-module-jackson</artifactId>
	</dependency>
	<dependency>
		<groupId>tools.jackson.core</groupId>
		<artifactId>jackson-databind</artifactId>
	</dependency>
	<dependency>
	    <groupId>com.github.victools</groupId>
	    <artifactId>jsonschema-generator</artifactId>
	</dependency>
	
	<dependency>
        <groupId>openup</groupId>
        <artifactId>EPF-naming</artifactId>
        <version>${project.version}</version>
    </dependency>
    <dependency>
		<groupId>openup</groupId>
		<artifactId>EPF-persistence-schema</artifactId>
		<version>${project.version}</version>
	</dependency>
    <dependency>
		<groupId>openup</groupId>
		<artifactId>EPF-query-schema</artifactId>
		<version>${project.version}</version>
	</dependency>
  </dependencies>
</project>
