quarkus.index-dependency.EPF-messaging-utility-ext.group-id=openup
quarkus.index-dependency.EPF-messaging-utility-ext.artifact-id=EPF-messaging-utility-ext
quarkus.index-dependency.EPF-schema-utility.group-id=openup
quarkus.index-dependency.EPF-schema-utility.artifact-id=EPF-schema-utility
quarkus.hibernate-orm.multitenant=DATABASE
quarkus.hibernate-orm.database.start-offline=true
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.packages=epf.delivery_processes.schema,epf.roles.schema,epf.tasks.schema,epf.work_products.schema,epf.schema.utility
quarkus.default-locale=en-US
quarkus.container-image.group=epf
quarkus.container-image.name=epf-persistence
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.name=epf-persistence
quarkus.http.port=9181
quarkus.jib.ports=9181
quarkus.kubernetes.ports."http".container-port=9181
quarkus.kubernetes.ports."http".host-port=9181
quarkus.kubernetes.remote-debug.address-port=5007
quarkus.kubernetes.resources.requests.cpu=25m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=250m
quarkus.kubernetes.resources.limits.memory=256Mi
quarkus.lra.coordinator-url=http://localhost:50000/lra-coordinator
quarkus.kubernetes.env.vars.quarkus-lra-coordinator-url=http://epf-transaction:50000/lra-coordinator
quarkus.kubernetes.env.vars.mp-messaging-connector-smallrye-kafka-security-protocol=SASL_PLAINTEXT
quarkus.kubernetes.env.vars.mp-messaging-connector-smallrye-kafka-sasl-mechanism=SCRAM-SHA-256
quarkus.kubernetes.env.vars.mp-messaging-connector-smallrye-kafka-sasl-jaas-config=org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="090323508";
quarkus.kubernetes.env.vars.mp-messaging-connector-smallrye-kafka-bootstrap-servers=kafka-controller-0.kafka-controller-headless:9092
epf.datasource.jdbc.url.format=jdbc:postgresql://localhost:6543/%s?sslmode=disable
epf.datasource.connection.pool.size=10
quarkus.kubernetes.env.vars.EPF_DATASOURCE_JDBC_URL_FORMAT=jdbc:postgresql://supavisor:6543/%s?sslmode=disable
quarkus.redis.hosts=redis://localhost:6379
quarkus.redis.password=090323508
quarkus.kubernetes.env.vars.QUARKUS_REDIS_HOSTS=redis://redis-master:6379
quarkus.kubernetes.env.mapping.QUARKUS_REDIS_PASSWORD.from-secret=redis
quarkus.kubernetes.env.mapping.QUARKUS_REDIS_PASSWORD.with-key=redis-password
quarkus.kubernetes.env.vars.MP_JWT_VERIFY_PUBLICKEY_LOCATION=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev/protocol/openid-connect/certs
quarkus.kubernetes.env.vars.MP_JWT_VERIFY_ISSUER=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev
quarkus.kubernetes.env.vars.QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.helm.name=epf-persistence
quarkus.log.level=TRACE