---
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: epf-feature
spec:
  flagSpec:
    flags: {}
---
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlagSource
metadata:
  name: epf-feature
spec:
  sources:
  - source: epf-feature
    provider: kubernetes