quarkus.container-image.group=epf
quarkus.container-image.name=frp
quarkus.kubernetes.name=frp
quarkus.http.port=7000
quarkus.jib.ports=7000,7002,2200,7500
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=7000
quarkus.kubernetes.ports."http".host-port=7000
quarkus.kubernetes.ports."https".container-port=2200
quarkus.kubernetes.ports."https".host-port=2200
quarkus.kubernetes.ports."https".tls=true
quarkus.kubernetes.ports."quic".container-port=7002
quarkus.kubernetes.ports."quic".host-port=7002
quarkus.kubernetes.ports."web".container-port=7500
quarkus.kubernetes.ports."web".host-port=7500
quarkus.kubernetes.resources.requests.cpu=25m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.helm.name=frp
#quarkus.kubernetes.service-type=load-balancer
quarkus.kubernetes.mounts.frp-config.path=/config
quarkus.kubernetes.config-map-volumes.frp-config.config-map-name=frp
quarkus.kubernetes.arguments=-c,/config/frps
quarkus.kubernetes.ingress.expose=false
quarkus.kubernetes.ingress.ingress-class-name=haproxy
quarkus.kubernetes.ingress.host=*.localhost.direct
quarkus.kubernetes.ingress.target-port=https
quarkus.kubernetes.ingress.annotations."ingress.kubernetes.io/ssl-passthrough"=true
quarkus.kubernetes.ingress.annotations."ingress.kubernetes.io/send-proxy-protocol"=proxy-v2-ssl-cn
quarkus.kubernetes.ingress.tls.frp-tls.enabled=true
quarkus.kubernetes.ingress.tls.frp-tls.hosts=*.localhost.direct
quarkus.kubernetes.secret-volumes.frp-tls.secret-name=frp-tls
quarkus.kubernetes.mounts.frp-tls.path=/frp-tls