quarkus.container-image.group=epf
quarkus.container-image.name=frp
quarkus.kubernetes.name=frp
quarkus.http.port=7000
quarkus.jib.ports=7000,7002,2200,7500
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=7000
quarkus.kubernetes.ports."http".host-port=7000
quarkus.kubernetes.ports."quic".container-port=7002
quarkus.kubernetes.ports."quic".host-port=7002
quarkus.kubernetes.ports."web".container-port=7500
quarkus.kubernetes.ports."web".host-port=7500
quarkus.kubernetes.ports."ssh".container-port=2200
quarkus.kubernetes.ports."ssh".host-port=2200
quarkus.kubernetes.resources.requests.cpu=25m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.kubernetes.service-type=load-balancer
quarkus.helm.name=frp
quarkus.kubernetes.mounts.epf-config.path=/epf/config
quarkus.kubernetes.config-map-volumes."epf-config".config-map-name=frp
quarkus.kubernetes.config-map-volumes."epf-config".items."frps.toml".path=frps.toml
quarkus.kubernetes.arguments=-c /epf/config/frps.toml