apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: openup
  labels:
    app.kubernetes.io/name: openup
    app.kubernetes.io/version: 1.0.0
spec:
  applicationImage: openup:1.0.0
  service:
    port: 9080
  expose: true
  route:
    pathType: ImplementationSpecific
  env:
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: "simple"
    - name: WLP_LOGGING_CONSOLE_SOURCE
      value: "message,trace,accessLog,ffdc,audit"
    - name: WLP_DEBUG_SUSPEND
      value: "n"
    - name: WLP_DEBUG_ADDRESS
      value: "7777"
  probes:
    liveness:
      failureThreshold: 12
      httpGet:
        path: /health/live
        port: 9080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 10
    readiness:
      failureThreshold: 12
      httpGet:
        path: /health/ready
        port: 9080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 10
  volumeMounts:
  - name: openup
    mountPath: /openup
    subPath: openup
  statefulSet:
    storage:
      volumeClaimTemplate:
        metadata:
          name: openup
        spec:
          accessModes:
          - "ReadWriteOnce"
          storageClassName: 'hostpath'
          resources:
            requests:
              storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: openup
    app.kubernetes.io/version: 1.0.0
  name: openup
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: "hostpath"
  hostPath:
    path: "/var/lib/k8s-pvs/openup"
    type: ""
  capacity:  
    storage: 1Gi