apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  labels:
    app.kubernetes.io/name: openup
    app.kubernetes.io/version: 1.0.0
  name: openup
spec:
  applicationImage: openup:1.0.0
  service:
    port: 9080
  expose: true
  route:
    pathType: ImplementationSpecific
  env:
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: "simple"
    - name: WLP_LOGGING_CONSOLE_SOURCE
      value: "message,trace,accessLog,ffdc,audit"
  probes:
    liveness:
      failureThreshold: 12
      httpGet:
        path: /health/live
        port: 9080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 10
    readiness:
      failureThreshold: 12
      httpGet:
        path: /health/ready
        port: 9080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 10