apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: openup
    app.kubernetes.io/version: 1.0.0
  name: openup
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: "hostpath"
  hostPath:
    path: "/var/lib/k8s-pvs/openup"
    type: ""
  capacity:  
    storage: 1Gi