package epf.persistence.remote;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.rmi.RemoteException;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Date;
import java.sql.NClob;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Statement;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;

public interface RemoteResultSet extends ResultSet, RemoteWrapper {
    boolean _next() throws RemoteException, SQLException;
    void _close() throws RemoteException, SQLException;
    boolean _wasNull() throws RemoteException, SQLException;
    String _getString(int columnIndex) throws RemoteException, SQLException;
    boolean _getBoolean(int columnIndex) throws RemoteException, SQLException;
    byte _getByte(int columnIndex) throws RemoteException, SQLException;
    short _getShort(int columnIndex) throws RemoteException, SQLException;
    int _getInt(int columnIndex) throws RemoteException, SQLException;
    long _getLong(int columnIndex) throws RemoteException, SQLException;
    float _getFloat(int columnIndex) throws RemoteException, SQLException;
    double _getDouble(int columnIndex) throws RemoteException, SQLException;
    BigDecimal _getBigDecimal(int columnIndex, int scale) throws RemoteException, SQLException;
    byte[] _getBytes(int columnIndex) throws RemoteException, SQLException;
    Date _getDate(int columnIndex) throws RemoteException, SQLException;
    Time _getTime(int columnIndex) throws RemoteException, SQLException;
    Timestamp _getTimestamp(int columnIndex) throws RemoteException, SQLException;
    InputStream _getAsciiStream(int columnIndex) throws RemoteException, SQLException;
    InputStream _getUnicodeStream(int columnIndex) throws RemoteException, SQLException;
    InputStream _getBinaryStream(int columnIndex) throws RemoteException, SQLException;
    String _getString(String columnLabel) throws RemoteException, SQLException;
    boolean _getBoolean(String columnLabel) throws RemoteException, SQLException;
    byte _getByte(String columnLabel) throws RemoteException, SQLException;
    short _getShort(String columnLabel) throws RemoteException, SQLException;
    int _getInt(String columnLabel) throws RemoteException, SQLException;
    long _getLong(String columnLabel) throws RemoteException, SQLException;
    float _getFloat(String columnLabel) throws RemoteException, SQLException;
    double _getDouble(String columnLabel) throws RemoteException, SQLException;
    BigDecimal _getBigDecimal(String columnLabel, int scale) throws RemoteException, SQLException;
    byte[] _getBytes(String columnLabel) throws RemoteException, SQLException;
    Date _getDate(String columnLabel) throws RemoteException, SQLException;
    Time _getTime(String columnLabel) throws RemoteException, SQLException;
    Timestamp _getTimestamp(String columnLabel) throws RemoteException, SQLException;
    InputStream _getAsciiStream(String columnLabel) throws RemoteException, SQLException;
    InputStream _getUnicodeStream(String columnLabel) throws RemoteException, SQLException;
    InputStream _getBinaryStream(String columnLabel) throws RemoteException, SQLException;
    SQLWarning _getWarnings() throws RemoteException, SQLException;
    void _clearWarnings() throws RemoteException, SQLException;
    String _getCursorName() throws RemoteException, SQLException;
    ResultSetMetaData _getMetaData() throws RemoteException, SQLException;
    Object _getObject(int columnIndex) throws RemoteException, SQLException;
    Object _getObject(String columnLabel) throws RemoteException, SQLException;
    int _findColumn(String columnLabel) throws RemoteException, SQLException;
    Reader _getCharacterStream(int columnIndex) throws RemoteException, SQLException;
    Reader _getCharacterStream(String columnLabel) throws RemoteException, SQLException;
    BigDecimal _getBigDecimal(int columnIndex) throws RemoteException, SQLException;
    BigDecimal _getBigDecimal(String columnLabel) throws RemoteException, SQLException;
    boolean _isBeforeFirst() throws RemoteException, SQLException;
    boolean _isAfterLast() throws RemoteException, SQLException;
    boolean _isFirst() throws RemoteException, SQLException;
    boolean _isLast() throws RemoteException, SQLException;
    void _beforeFirst() throws RemoteException, SQLException;
    void _afterLast() throws RemoteException, SQLException;
    boolean _first() throws RemoteException, SQLException;
    boolean _last() throws RemoteException, SQLException;
    int _getRow() throws RemoteException, SQLException;
    boolean _absolute( int row ) throws RemoteException, SQLException;
    boolean _relative( int rows ) throws RemoteException, SQLException;
    boolean _previous() throws RemoteException, SQLException;
    void _setFetchDirection(int direction) throws RemoteException, SQLException;
    int _getFetchDirection() throws RemoteException, SQLException;
    void _setFetchSize(int rows) throws RemoteException, SQLException;
    int _getFetchSize() throws RemoteException, SQLException;
    int _getType() throws RemoteException, SQLException;
    int _getConcurrency() throws RemoteException, SQLException;
    boolean _rowUpdated() throws RemoteException, SQLException;
    boolean _rowInserted() throws RemoteException, SQLException;
    boolean _rowDeleted() throws RemoteException, SQLException;
    void _updateNull(int columnIndex) throws RemoteException, SQLException;
    void _updateBoolean(int columnIndex, boolean x) throws RemoteException, SQLException;
    void _updateByte(int columnIndex, byte x) throws RemoteException, SQLException;
    void _updateShort(int columnIndex, short x) throws RemoteException, SQLException;
    void _updateInt(int columnIndex, int x) throws RemoteException, SQLException;
    void _updateLong(int columnIndex, long x) throws RemoteException, SQLException;
    void _updateFloat(int columnIndex, float x) throws RemoteException, SQLException;
    void _updateDouble(int columnIndex, double x) throws RemoteException, SQLException;
    void _updateBigDecimal(int columnIndex, BigDecimal x) throws RemoteException, SQLException;
    void _updateString(int columnIndex, String x) throws RemoteException, SQLException;
    void _updateBytes(int columnIndex, byte x[]) throws RemoteException, SQLException;
    void _updateDate(int columnIndex, java.sql.Date x) throws RemoteException, SQLException;
    void _updateTime(int columnIndex, java.sql.Time x) throws RemoteException, SQLException;
    void _updateTimestamp(int columnIndex, java.sql.Timestamp x) throws RemoteException, SQLException;
    void _updateAsciiStream(int columnIndex, java.io.InputStream x, int length) throws RemoteException, SQLException;
    void _updateBinaryStream(int columnIndex, java.io.InputStream x, int length) throws RemoteException, SQLException;
    void _updateCharacterStream(int columnIndex, java.io.Reader x, int length) throws RemoteException, SQLException;
    void _updateObject(int columnIndex, Object x, int scaleOrLength) throws RemoteException, SQLException;
    void _updateObject(int columnIndex, Object x) throws RemoteException, SQLException;
    void _updateNull(String columnLabel) throws RemoteException, SQLException;
    void _updateBoolean(String columnLabel, boolean x) throws RemoteException, SQLException;
    void _updateByte(String columnLabel, byte x) throws RemoteException, SQLException;
    void _updateShort(String columnLabel, short x) throws RemoteException, SQLException;
    void _updateInt(String columnLabel, int x) throws RemoteException, SQLException;
    void _updateLong(String columnLabel, long x) throws RemoteException, SQLException;
    void _updateFloat(String columnLabel, float x) throws RemoteException, SQLException;
    void _updateDouble(String columnLabel, double x) throws RemoteException, SQLException;
    void _updateBigDecimal(String columnLabel, BigDecimal x) throws RemoteException, SQLException;
    void _updateString(String columnLabel, String x) throws RemoteException, SQLException;
    void _updateBytes(String columnLabel, byte x[]) throws RemoteException, SQLException;
    void _updateDate(String columnLabel, java.sql.Date x) throws RemoteException, SQLException;
    void _updateTime(String columnLabel, java.sql.Time x) throws RemoteException, SQLException;
    void _updateTimestamp(String columnLabel, java.sql.Timestamp x) throws RemoteException, SQLException;
    void _updateAsciiStream(String columnLabel, java.io.InputStream x, int length) throws RemoteException, SQLException;
    void _updateBinaryStream(String columnLabel, java.io.InputStream x, int length) throws RemoteException, SQLException;
    void _updateCharacterStream(String columnLabel, java.io.Reader reader, int length) throws RemoteException, SQLException;
    void _updateObject(String columnLabel, Object x, int scaleOrLength) throws RemoteException, SQLException;
    void _updateObject(String columnLabel, Object x) throws RemoteException, SQLException;
    void _insertRow() throws RemoteException, SQLException;
    void _updateRow() throws RemoteException, SQLException;
    void _deleteRow() throws RemoteException, SQLException;
    void _refreshRow() throws RemoteException, SQLException;
    void _cancelRowUpdates() throws RemoteException, SQLException;
    void _moveToInsertRow() throws RemoteException, SQLException;
    void _moveToCurrentRow() throws RemoteException, SQLException;
    Statement _getStatement() throws RemoteException, SQLException;
    Object _getObject(int columnIndex, java.util.Map<String,Class<?>> map) throws RemoteException, SQLException;
    Ref _getRef(int columnIndex) throws RemoteException, SQLException;
    Blob _getBlob(int columnIndex) throws RemoteException, SQLException;
    Clob _getClob(int columnIndex) throws RemoteException, SQLException;
    Array _getArray(int columnIndex) throws RemoteException, SQLException;
    Object _getObject(String columnLabel, java.util.Map<String,Class<?>> map) throws RemoteException, SQLException;
    Ref _getRef(String columnLabel) throws RemoteException, SQLException;
    Blob _getBlob(String columnLabel) throws RemoteException, SQLException;
    Clob _getClob(String columnLabel) throws RemoteException, SQLException;
    Array _getArray(String columnLabel) throws RemoteException, SQLException;
    java.sql.Date _getDate(int columnIndex, Calendar cal) throws RemoteException, SQLException;
    java.sql.Date _getDate(String columnLabel, Calendar cal) throws RemoteException, SQLException;
    java.sql.Time _getTime(int columnIndex, Calendar cal) throws RemoteException, SQLException;
    java.sql.Time _getTime(String columnLabel, Calendar cal) throws RemoteException, SQLException;
    java.sql.Timestamp _getTimestamp(int columnIndex, Calendar cal) throws RemoteException, SQLException;
    java.sql.Timestamp _getTimestamp(String columnLabel, Calendar cal) throws RemoteException, SQLException;
    java.net.URL _getURL(int columnIndex) throws RemoteException, SQLException;
    java.net.URL _getURL(String columnLabel) throws RemoteException, SQLException;
    void _updateRef(int columnIndex, java.sql.Ref x) throws RemoteException, SQLException;
    void _updateRef(String columnLabel, java.sql.Ref x) throws RemoteException, SQLException;
    void _updateBlob(int columnIndex, java.sql.Blob x) throws RemoteException, SQLException;
    void _updateBlob(String columnLabel, java.sql.Blob x) throws RemoteException, SQLException;
    void _updateClob(int columnIndex, java.sql.Clob x) throws RemoteException, SQLException;
    void _updateClob(String columnLabel, java.sql.Clob x) throws RemoteException, SQLException;
    void _updateArray(int columnIndex, java.sql.Array x) throws RemoteException, SQLException;
    void _updateArray(String columnLabel, java.sql.Array x) throws RemoteException, SQLException;
    RowId _getRowId(int columnIndex) throws RemoteException, SQLException;
    RowId _getRowId(String columnLabel) throws RemoteException, SQLException;
    void _updateRowId(int columnIndex, RowId x) throws RemoteException, SQLException;
    void _updateRowId(String columnLabel, RowId x) throws RemoteException, SQLException;
    int _getHoldability() throws RemoteException, SQLException;
    boolean _isClosed() throws RemoteException, SQLException;
    void _updateNString(int columnIndex, String nString) throws RemoteException, SQLException;
    void _updateNString(String columnLabel, String nString) throws RemoteException, SQLException;
    void _updateNClob(int columnIndex, NClob nClob) throws RemoteException, SQLException;
    void _updateNClob(String columnLabel, NClob nClob) throws RemoteException, SQLException;
    NClob _getNClob(int columnIndex) throws RemoteException, SQLException;
    NClob _getNClob(String columnLabel) throws RemoteException, SQLException;
    SQLXML _getSQLXML(int columnIndex) throws RemoteException, SQLException;
    SQLXML _getSQLXML(String columnLabel) throws RemoteException, SQLException;
    void _updateSQLXML(int columnIndex, SQLXML xmlObject) throws RemoteException, SQLException;
    void _updateSQLXML(String columnLabel, SQLXML xmlObject) throws RemoteException, SQLException;
    String _getNString(int columnIndex) throws RemoteException, SQLException;
    String _getNString(String columnLabel) throws RemoteException, SQLException;
    java.io.Reader _getNCharacterStream(int columnIndex) throws RemoteException, SQLException;
    java.io.Reader _getNCharacterStream(String columnLabel) throws RemoteException, SQLException;
    void _updateNCharacterStream(int columnIndex, java.io.Reader x, long length) throws RemoteException, SQLException;
    void _updateNCharacterStream(String columnLabel, java.io.Reader reader, long length) throws RemoteException, SQLException;
    void _updateAsciiStream(int columnIndex, java.io.InputStream x, long length) throws RemoteException, SQLException;
    void _updateBinaryStream(int columnIndex, java.io.InputStream x, long length) throws RemoteException, SQLException;
    void _updateCharacterStream(int columnIndex, java.io.Reader x, long length) throws RemoteException, SQLException;
    void _updateAsciiStream(String columnLabel, java.io.InputStream x, long length) throws RemoteException, SQLException;
    void _updateBinaryStream(String columnLabel, java.io.InputStream x, long length) throws RemoteException, SQLException;
    void _updateCharacterStream(String columnLabel, java.io.Reader reader, long length) throws RemoteException, SQLException;
    void _updateBlob(int columnIndex, InputStream inputStream, long length) throws RemoteException, SQLException;
    void _updateBlob(String columnLabel, InputStream inputStream, long length) throws RemoteException, SQLException;
    void _updateClob(int columnIndex,  Reader reader, long length) throws RemoteException, SQLException;
    void _updateClob(String columnLabel,  Reader reader, long length) throws RemoteException, SQLException;
    void _updateNClob(int columnIndex,  Reader reader, long length) throws RemoteException, SQLException;
    void _updateNClob(String columnLabel,  Reader reader, long length) throws RemoteException, SQLException;
    void _updateNCharacterStream(int columnIndex, java.io.Reader x) throws RemoteException, SQLException;
    void _updateNCharacterStream(String columnLabel, java.io.Reader reader) throws RemoteException, SQLException;
    void _updateAsciiStream(int columnIndex, java.io.InputStream x) throws RemoteException, SQLException;
    void _updateBinaryStream(int columnIndex, java.io.InputStream x) throws RemoteException, SQLException;
    void _updateCharacterStream(int columnIndex, java.io.Reader x) throws RemoteException, SQLException;
    void _updateAsciiStream(String columnLabel, java.io.InputStream x) throws RemoteException, SQLException;
    void _updateBinaryStream(String columnLabel, java.io.InputStream x) throws RemoteException, SQLException;
    void _updateCharacterStream(String columnLabel, java.io.Reader reader) throws RemoteException, SQLException;
    void _updateBlob(int columnIndex, InputStream inputStream) throws RemoteException, SQLException;
    void _updateBlob(String columnLabel, InputStream inputStream) throws RemoteException, SQLException;
    void _updateClob(int columnIndex,  Reader reader) throws RemoteException, SQLException;
    void _updateClob(String columnLabel,  Reader reader) throws RemoteException, SQLException;
    void _updateNClob(int columnIndex,  Reader reader) throws RemoteException, SQLException;
    void _updateNClob(String columnLabel,  Reader reader) throws RemoteException, SQLException;
    <T> T _getObject(int columnIndex, Class<T> type) throws RemoteException, SQLException;
    <T> T _getObject(String columnLabel, Class<T> type) throws RemoteException, SQLException;
}
