package epf.persistence.remote;

import java.rmi.RemoteException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

public interface RemoteStatement extends Statement, RemoteWrapper {
    RemoteResultSet _executeQuery(final String sql) throws RemoteException, SQLException;
    int _executeUpdate(String sql) throws RemoteException, SQLException;
    void _close() throws RemoteException, SQLException;
    int _getMaxFieldSize() throws RemoteException, SQLException;
    void _setMaxFieldSize(int max) throws RemoteException, SQLException;
    int _getMaxRows() throws RemoteException, SQLException;
    void _setMaxRows(int max) throws RemoteException, SQLException;
    void _setEscapeProcessing(boolean enable) throws RemoteException, SQLException;
    int _getQueryTimeout() throws RemoteException, SQLException;
    void _setQueryTimeout(int seconds) throws RemoteException, SQLException;
    void _cancel() throws RemoteException, SQLException;
    SQLWarning _getWarnings() throws RemoteException, SQLException;
    void _clearWarnings() throws RemoteException, SQLException;
    void _setCursorName(String name) throws RemoteException, SQLException;
    boolean _execute(String sql) throws RemoteException, SQLException;
    RemoteResultSet _getResultSet() throws RemoteException, SQLException;
    int _getUpdateCount() throws RemoteException, SQLException;
    boolean _getMoreResults() throws RemoteException, SQLException;
    void _setFetchDirection(int direction) throws RemoteException, SQLException;
    int _getFetchDirection() throws RemoteException, SQLException;
    void _setFetchSize(int rows) throws RemoteException, SQLException;
    int _getFetchSize() throws RemoteException, SQLException;
    int _getResultSetConcurrency() throws RemoteException, SQLException;
    int _getResultSetType() throws RemoteException, SQLException;
    void _addBatch( String sql ) throws RemoteException, SQLException;
    void _clearBatch() throws RemoteException, SQLException;
    int[] _executeBatch() throws RemoteException, SQLException;
    RemoteConnection _getConnection()  throws RemoteException, SQLException;
    boolean _getMoreResults(int current) throws RemoteException, SQLException;
    RemoteResultSet _getGeneratedKeys() throws RemoteException, SQLException;
    int _executeUpdate(String sql, int autoGeneratedKeys) throws RemoteException, SQLException;
    int _executeUpdate(String sql, int columnIndexes[]) throws RemoteException, SQLException;
    int _executeUpdate(String sql, String columnNames[]) throws RemoteException, SQLException;
    boolean _execute(String sql, int autoGeneratedKeys) throws RemoteException, SQLException;
    boolean _execute(String sql, int columnIndexes[]) throws RemoteException, SQLException;
    boolean _execute(String sql, String columnNames[]) throws RemoteException, SQLException;
    int _getResultSetHoldability() throws RemoteException, SQLException;
    boolean _isClosed() throws RemoteException, SQLException;
    void _setPoolable(boolean poolable)
                throws RemoteException, SQLException;
    boolean _isPoolable()
                throws RemoteException, SQLException;
    void _closeOnCompletion() throws RemoteException, SQLException;
    boolean _isCloseOnCompletion() throws RemoteException, SQLException;
}
