quarkus.container-image.group=epf
quarkus.container-image.name=epf-logging
quarkus.kubernetes.name=epf-logging
quarkus.jib.ports=8080
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=8080
quarkus.kubernetes.ports."http".host-port=8080
quarkus.kubernetes.env.vars.QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-collector:4317
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.helm.name=epf-logging