apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-proxy
  namespace: default
  annotations:
    ingress.kubernetes.io/server-ssl: "true"
    ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: "haproxy"
  rules:
    - host: chipmunk-capable-prawn.ngrok-free.app
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8443
