apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-proxy
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: 
      set $new_host "$arg_org.$best_http_host";
      proxy_set_header HOST $new_host;
      proxy_set_header X-Forwarded-Host $new_host;
      proxy_set_header X-Original-Forwarded-Host $new_host;

spec:
  ingressClassName: "nginx"
  rules:
    - host: chipmunk-capable-prawn.ngrok-free.app
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 443
    - host: "*.localhost"
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 443
