mp.messaging.incoming.epf-persistence-event.connector=smallrye-kafka
mp.messaging.incoming.epf-persistence-event.topic=epf.persistence.event
mp.messaging.incoming.epf-persistence-event.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.epf-persistence-event.value.deserializer=epf.messaging.util.ext.io.JsonDeserializer
mp.messaging.incoming.epf-persistence-event.group.id=epf-query
mp.messaging.incoming.epf-persistence-event.max.poll.interval.ms=2000000
mp.jwt.verify.issuer=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev
mp.jwt.verify.publickey.location=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev/protocol/openid-connect/certs