CREATE ALIAS IF NOT EXISTS FT_INIT FOR "org.h2.fulltext.FullText.init";
CALL FT_INIT();

/**/
CALL FT_DROP_INDEX('EPF', 'DELIVERY_PROCESS');
CALL FT_DROP_INDEX('EPF', 'PHASE');
CALL FT_DROP_INDEX('EPF', 'CAPABILITY_PATTERN');
CALL FT_DROP_INDEX('EPF', 'ACTIVITY');
CALL FT_DROP_INDEX('EPF', 'ITERATION');
CALL FT_DROP_INDEX('EPF', 'ITERATION_ACTIVITIES');
CALL FT_DROP_INDEX('EPF', 'MILESTONE');
CALL FT_DROP_INDEX('EPF', 'ROLE_SET');
CALL FT_DROP_INDEX('EPF', 'EPF_ROLE');
CALL FT_DROP_INDEX('EPF', 'ROLES');
CALL FT_DROP_INDEX('EPF', 'EPF_DOMAIN');
CALL FT_DROP_INDEX('EPF', 'ARTIFACT');
CALL FT_DROP_INDEX('EPF', 'DELIVERABLE');
CALL FT_DROP_INDEX('EPF', 'WORK_PRODUCTS');
CALL FT_DROP_INDEX('EPF', 'WORK_PRODUCT_SLOT');
CALL FT_DROP_INDEX('EPF', 'DISCIPLINE');
CALL FT_DROP_INDEX('EPF', 'TASK');
CALL FT_DROP_INDEX('EPF', 'TASKS');
CALL FT_DROP_INDEX('EPF', 'ROLE_ADDITIONALLY_PERFORMS');
CALL FT_DROP_INDEX('EPF', 'ROLE_MODIFIES');
CALL FT_DROP_INDEX('EPF', 'ARTIFACT_FULFILLED_SLOTS');
CALL FT_DROP_INDEX('EPF', 'TASK_INPUTS_MANDATORY');
CALL FT_DROP_INDEX('EPF', 'TASK_INPUTS_OPTIONAL');
CALL FT_DROP_INDEX('EPF', 'TASK_OUTPUTS');
/**/

/**/
CALL FT_CREATE_INDEX('EPF', 'DELIVERY_PROCESS', NULL);
CALL FT_CREATE_INDEX('EPF', 'PHASE', NULL);
CALL FT_CREATE_INDEX('EPF', 'CAPABILITY_PATTERN', NULL);
CALL FT_CREATE_INDEX('EPF', 'ACTIVITY', NULL);
CALL FT_CREATE_INDEX('EPF', 'ITERATION', NULL);
CALL FT_CREATE_INDEX('EPF', 'ITERATION_ACTIVITIES', NULL);
CALL FT_CREATE_INDEX('EPF', 'MILESTONE', NULL);
CALL FT_CREATE_INDEX('EPF', 'ROLE_SET', NULL);
CALL FT_CREATE_INDEX('EPF', 'EPF_ROLE', NULL);
CALL FT_CREATE_INDEX('EPF', 'ROLES', NULL);
CALL FT_CREATE_INDEX('EPF', 'EPF_DOMAIN', NULL);
CALL FT_CREATE_INDEX('EPF', 'ARTIFACT', NULL);
CALL FT_CREATE_INDEX('EPF', 'DELIVERABLE', NULL);
CALL FT_CREATE_INDEX('EPF', 'WORK_PRODUCTS', NULL);
CALL FT_CREATE_INDEX('EPF', 'WORK_PRODUCT_SLOT', NULL);
CALL FT_CREATE_INDEX('EPF', 'DISCIPLINE', NULL);
CALL FT_CREATE_INDEX('EPF', 'TASK', NULL);
CALL FT_CREATE_INDEX('EPF', 'TASKS', NULL);
CALL FT_CREATE_INDEX('EPF', 'ROLE_ADDITIONALLY_PERFORMS', NULL);
CALL FT_CREATE_INDEX('EPF', 'ROLE_MODIFIES', NULL);
CALL FT_CREATE_INDEX('EPF', 'ARTIFACT_FULFILLED_SLOTS', NULL);
CALL FT_CREATE_INDEX('EPF', 'TASK_INPUTS_MANDATORY', NULL);
CALL FT_CREATE_INDEX('EPF', 'TASK_INPUTS_OPTIONAL', NULL);
CALL FT_CREATE_INDEX('EPF', 'TASK_OUTPUTS', NULL);
/**/

/**/
CALL FT_DROP_INDEX('OPENUP', 'OPENUP_ACTIVITY');
CALL FT_DROP_INDEX('OPENUP', 'OPENUP_ARTIFACT');
CALL FT_DROP_INDEX('OPENUP', 'OPENUP_DELIVERY_PROCESS');
CALL FT_DROP_INDEX('OPENUP', 'OPENUP_ITERATION');
CALL FT_DROP_INDEX('OPENUP', 'OPENUP_MILESTONE');
CALL FT_DROP_INDEX('OPENUP', 'OPENUP_PHASE');
CALL FT_DROP_INDEX('OPENUP', 'OPENUP_ROLE');
CALL FT_DROP_INDEX('OPENUP', 'OPENUP_ROLE_SET');
CALL FT_DROP_INDEX('OPENUP', 'OPENUP_ROLE_MODIFIES');
CALL FT_DROP_INDEX('OPENUP', 'OPENUP_TASK');
/**/

/**/
CALL FT_CREATE_INDEX('OPENUP', 'OPENUP_ACTIVITY', NULL);
CALL FT_CREATE_INDEX('OPENUP', 'OPENUP_ARTIFACT', NULL);
CALL FT_CREATE_INDEX('OPENUP', 'OPENUP_DELIVERY_PROCESS', NULL);
CALL FT_CREATE_INDEX('OPENUP', 'OPENUP_ITERATION', NULL);
CALL FT_CREATE_INDEX('OPENUP', 'OPENUP_MILESTONE', NULL);
CALL FT_CREATE_INDEX('OPENUP', 'OPENUP_PHASE', NULL);
CALL FT_CREATE_INDEX('OPENUP', 'OPENUP_ROLE', NULL);
CALL FT_CREATE_INDEX('OPENUP', 'OPENUP_ROLE_SET', NULL);
CALL FT_CREATE_INDEX('OPENUP', 'OPENUP_ROLE_MODIFIES', NULL);
CALL FT_CREATE_INDEX('OPENUP', 'OPENUP_TASK', NULL);
/**/