CREATE SCHEMA IF NOT EXISTS EPF_Delivery_Processes;
CREATE SCHEMA IF NOT EXISTS EPF_Roles;
CREATE SCHEMA IF NOT EXISTS EPF_Tasks;
CREATE SCHEMA IF NOT EXISTS EPF_Work_Products;
CREATE SCHEMA IF NOT EXISTS OpenUP;