---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: scylla
    app.kubernetes.io/version: 1.0.0
  name: scylla
spec:
  ports:
    - name: scylla
      port: 9042
      targetPort: 9042
  selector:
    app.kubernetes.io/name: scylla
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: scylla
    app.kubernetes.io/version: 1.0.0
  name: scylla
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scylla
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scylla
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: "scylladb/scylla:latest"
          imagePullPolicy: IfNotPresent
          name: scylla
          ports:
            - containerPort: 9042
              name: scylla
              protocol: TCP
