---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration: {}
      # useEmulation: true
      # featureGates:
        # - "Root"
    imagePullPolicy: IfNotPresent
  customizeComponents:
    flags:
      handler:
        # kubelet-root: "/var/snap/microk8s/common/var/lib/kubelet"
        kubelet-pods-dir: "/var/snap/microk8s/common/var/lib/kubelet/pods"
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
