---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/version: 1.0.0
  name: ollama
spec:
  ports:
    - name: http
      port: 11434
      protocol: TCP
      targetPort: 11434
  selector:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/version: 1.0.0
  name: ollama
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: "hostpath"
  hostPath:
    path: "/ollama"
    type: "DirectoryOrCreate"
  capacity:  
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/version: 1.0.0
  name: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
  volumeName: "ollama"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/version: 1.0.0
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: ollama
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: ollama
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OLLAMA_MODELS
              value: "/root/.ollama/models"
            - name: OLLAMA_MAX_LOADED_MODELS
              value: "2"
          image: ollama/ollama:latest
          imagePullPolicy: IfNotPresent
          name: ollama
          ports:
            - containerPort: 11434
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /root/.ollama
              name: ollama
              readOnly: false
      volumes:
        - name: ollama
          persistentVolumeClaim:
            claimName: ollama
            readOnly: false
