---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: wildfly
    app.kubernetes.io/version: 1.0.0
  name: wildfly
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
  selector:
    app.kubernetes.io/name: wildfly
    app.kubernetes.io/version: 1.0.0
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: wildfly
    app.kubernetes.io/version: 1.0.0
  name: wildfly-internal
spec:
  ports:
    - name: admin
      port: 9990
      targetPort: 9990
    - name: debug
      port: 8787
      targetPort: 8787
  selector:
    app.kubernetes.io/name: wildfly
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: wildfly
    app.kubernetes.io/version: 1.0.0
  name: wildfly
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wildfly
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wildfly
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: epf_gateway_url
              value: "http://epf-gateway-internal.default.svc.cluster.local:8080/gateway/"
            - name: epf_config_url
              value: "http://epf-config.default.svc.cluster.local:9184/config/"
            - name: epf_webapp_url
              value: "https://localhost/webapp/"
            - name: epf_security_webapp_url
              value: "https://localhost/security/"
            - name: epf_client_net_ssl_keyStore
              value: "/dev.p12"
            - name: epf_client_net_ssl_keyStoreType
              value: "PKCS12"
            - name: epf_client_net_ssl_keyStorePassword
              value: "changeit"
            - name: epf_client_net_ssl_keyAlias
              value: "localhost"
            - name: epf_client_net_ssl_keyPassword
              value: "changeit"
            - name: epf_client_net_ssl_trustStore
              value: "/dev.p12"
            - name: epf_client_net_ssl_trustStoreType
              value: "PKCS12"
            - name: epf_client_net_ssl_trustStorePassword
              value: "changeit"
          image: "wildfly:1.0.0"
          imagePullPolicy: IfNotPresent
          name: wildfly
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 9990
              name: admin
              protocol: TCP
            - containerPort: 8787
              name: debug
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  labels:
    app.kubernetes.io/name: wildfly
    app.kubernetes.io/version: 1.0.0
  name: wildfly
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: wildfly
                port:
                  name: https
            path: /
            pathType: Prefix
