---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: wildfly
    app.kubernetes.io/version: 1.0.0
  name: wildfly
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: admin
      port: 9990
      targetPort: 9990
  selector:
    app.kubernetes.io/name: wildfly
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: wildfly
    app.kubernetes.io/version: 1.0.0
  name: wildfly
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wildfly
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wildfly
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: "wildfly:1.0.0"
          imagePullPolicy: IfNotPresent
          name: wildfly
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 9990
              name: admin
              protocol: TCP
