#kubectl create secret generic vllm --from-literal=hf-token=''
#helm repo add vllm https://vllm-project.github.io/production-stack
#helm install vllm vllm/vllm-stack -f values.yaml
kubectl delete secret vllm
kubectl create secret generic vllm --from-literal=VLLM_API_KEY='EMPTY'
kubectl apply -f vllm_dev.yaml
#docker run --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:latest --model neuralmagic/Mistral-7B-Instruct-v0.3-GPTQ-4bit --gpu-memory-utilization 0.87 --max_model_len 23200
#docker run --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" -p 8000:8000 --ipc=host vllm/vllm-openai:latest --model ModelCloud/Mistral-Nemo-Instruct-2407-gptq-4bit --gpu-memory-utilization 0.87
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.13.0 cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-4bit --gpu-memory-utilization 0.87 --tokenizer_mode mistral --config_format mistral --load_format mistral --enable-auto-tool-choice --tool-call-parser mistral
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.11.2 cyankiwi/granite-4.0-h-tiny-AWQ-4bit --gpu-memory-utilization 0.87 --max_model_len 16000 --enable-auto-tool-choice --tool-call-parser granite
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.11.2 RedHatAI/Mistral-Nemo-Instruct-2407-quantized.w4a16 --gpu-memory-utilization 0.87
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.11.2 /root/.cache/huggingface/Ministral-3-8B-Instruct-2512-Q4_K_M.gguf --tokenizer mistralai/Ministral-3-8B-Instruct-2512-Q4_K_M --gpu-memory-utilization 0.87
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.11.2 mistralai/Ministral-3-8B-Instruct-2512 --tokenizer_mode mistral --config_format mistral --load_format mistral --enable-auto-tool-choice --tool-call-parser mistral --gpu-memory-utilization 0.87 --max_model_len 16000
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.11.2 neuralmagic/granite-3.1-8b-instruct-quantized.w4a16 --gpu-memory-utilization 0.87 --max_model_len 14224 --enable-auto-tool-choice --tool-call-parser granite
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-4bit --gpu-memory-utilization 0.87 --max_model_len 8000 --tokenizer_mode mistral --config_format mistral --load_format mistral --enable-auto-tool-choice --tool-call-parser mistral --enable-lora
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai RedHatAI/granite-4.0-h-tiny-FP8-dynamic --gpu-memory-utilization 0.87 --enable-expert-parallel --enable-auto-tool-choice --tool-call-parser hermes --enable-lora
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai unsloth/Qwen2.5-7B-Instruct-bnb-4bit --gpu-memory-utilization 0.87 --kv-offloading-size 0.01 --enable-auto-tool-choice --tool-call-parser hermes --enable-lora
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.20.1 google/gemma-4-E2B-it --gpu-memory-utilization 0.87 --enable-auto-tool-choice --tool-call-parser gemma4  --enable-lora
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.20.1 unsloth/gemma-4-E2B-it-unsloth-bnb-4bit --gpu-memory-utilization 0.87 --enable-auto-tool-choice --tool-call-parser gemma4  --enable-lora --quantization bitsandbytes --load-format bitsandbytes --trust-remote-code --dtype half
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:gemma4-0505-cu130 unsloth/gemma-4-E2B-it-GGUF:Q4_K_M --gpu-memory-utilization 0.87 --enable-auto-tool-choice --tool-call-parser gemma4  --enable-lora --tokenizer google/gemma-4-E2B-it --trust-remote-code --enforce-eager
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.20.1 unsloth/granite-3.3-8b-instruct-GGUF:Q4_K_M --gpu-memory-utilization 0.87 --enable-auto-tool-choice --tool-call-parser granite --enable-lora --tokenizer ibm-granite/granite-3.3-8b-instruct --trust-remote-code
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.20.2 unsloth/NVIDIA-Nemotron-3-Nano-4B-GGUF:Q4_K_M --gpu-memory-utilization 0.87 --enable-auto-tool-choice --tool-call-parser qwen3_coder --enable-lora --tokenizer nvidia/NVIDIA-Nemotron-3-Nano-4B --trust-remote-code
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.20.1 ibm-granite/granite-4.1-8b-fp8 --gpu-memory-utilization 0.87 --max_model_len 9568 --enable-auto-tool-choice --tool-call-parser granite4 --enable-lora
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.21.0-x86_64-cu129-ubuntu2404 TevunahAi/Granite-3.3-8B-Instruct-GPTQ --gpu-memory-utilization 0.87 --max_model_len auto --enable-auto-tool-choice --tool-call-parser granite --enable-lora --served-model-name Granite-3.3-8B-Instruct-GPTQ


#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.21.0 mistralai/Ministral-3-3B-Instruct-2512 --gpu-memory-utilization 0.87 --max_model_len auto --enable-auto-tool-choice --tool-call-parser mistral --enable-lora --enforce-eager
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.21.0 Qwen/Qwen2.5-Coder-7B-Instruct-GPTQ-Int4 --gpu-memory-utilization 0.87 --max_model_len auto --enable-auto-tool-choice --tool-call-parser hermes --enable-lora --enforce-eager
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.21.0 Qwen/Qwen2.5-Coder-3B-Instruct-GPTQ-Int4 --gpu-memory-utilization 0.87 --max_model_len auto --enable-auto-tool-choice --tool-call-parser hermes --enable-lora --enforce-eager
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.21.0 unsloth/granite-4.1-3b-GGUF:Q4_K_M --gpu-memory-utilization 0.87 --max_model_len auto --enable-auto-tool-choice --tool-call-parser granite4 --enable-lora --tokenizer ibm-granite/granite-4.1-3b --trust-remote-code --enforce-eager
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.21.0 ibm-granite/granite-4.1-3b --gpu-memory-utilization 0.87 --max_model_len auto --enable-auto-tool-choice --tool-call-parser granite4 --enable-lora --enforce-eager
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:latest-cu130 google/gemma-4-E2B-it-qat-w4a16-ct --gpu-memory-utilization 0.87 --reasoning-parser gemma4 --enable-auto-tool-choice --tool-call-parser gemma4 --enable-lora --enforce-eager
kubectl run vllm --image=docker.io/vllm/vllm-openai:latest --env="HUGGING_FACE_HUB_TOKEN=" --env="VLLM_API_KEY=EMPTY" --env="VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" --override-type=strategic --overrides='{"spec":{"runtimeClassName":"nvidia","containers":[{"name":"vllm","image":"docker.io/vllm/vllm-openai:latest","resources":{"requests":{"nvidia.com/gpu":"1"},"limits":{"nvidia.com/gpu":"1"}}}]}}' --port=8000 --privileged=true  --restart='Never' -- google/gemma-4-E2B-it-qat-w4a16-ct --gpu-memory-utilization 0.87 --reasoning-parser gemma4 --enable-auto-tool-choice --tool-call-parser gemma4 --enable-lora --enforce-eager