#kubectl create secret generic vllm --from-literal=hf-token=''
#helm repo add vllm https://vllm-project.github.io/production-stack
#helm install vllm vllm/vllm-stack -f values.yaml
kubectl delete secret vllm
kubectl create secret generic vllm --from-literal=VLLM_API_KEY='EMPTY'
kubectl apply -f vllm_dev.yaml
#docker run --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:latest --model neuralmagic/Mistral-7B-Instruct-v0.3-GPTQ-4bit --gpu-memory-utilization 0.87 --max_model_len 23200
#docker run --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" -p 8000:8000 --ipc=host vllm/vllm-openai:latest --model ModelCloud/Mistral-Nemo-Instruct-2407-gptq-4bit --gpu-memory-utilization 0.87
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.13.0 cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-4bit --gpu-memory-utilization 0.87 --tokenizer_mode mistral --config_format mistral --load_format mistral --enable-auto-tool-choice --tool-call-parser mistral
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.11.2 cyankiwi/granite-4.0-h-tiny-AWQ-4bit --gpu-memory-utilization 0.87 --max_model_len 16000 --enable-auto-tool-choice --tool-call-parser granite
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.11.2 RedHatAI/Mistral-Nemo-Instruct-2407-quantized.w4a16 --gpu-memory-utilization 0.87
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.11.2 /root/.cache/huggingface/Ministral-3-8B-Instruct-2512-Q4_K_M.gguf --tokenizer mistralai/Ministral-3-8B-Instruct-2512-Q4_K_M --gpu-memory-utilization 0.87
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.11.2 mistralai/Ministral-3-8B-Instruct-2512 --tokenizer_mode mistral --config_format mistral --load_format mistral --enable-auto-tool-choice --tool-call-parser mistral --gpu-memory-utilization 0.87 --max_model_len 16000
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.11.2 neuralmagic/granite-3.1-8b-instruct-quantized.w4a16 --gpu-memory-utilization 0.87 --max_model_len 14224 --enable-auto-tool-choice --tool-call-parser granite
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-4bit --gpu-memory-utilization 0.87 --max_model_len 8000 --tokenizer_mode mistral --config_format mistral --load_format mistral --enable-auto-tool-choice --tool-call-parser mistral --enable-lora
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai RedHatAI/granite-4.0-h-tiny-FP8-dynamic --gpu-memory-utilization 0.87 --enable-expert-parallel --enable-auto-tool-choice --tool-call-parser hermes --enable-lora
#docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai unsloth/Qwen2.5-7B-Instruct-bnb-4bit --gpu-memory-utilization 0.87 --kv-offloading-size 0.01 --enable-auto-tool-choice --tool-call-parser hermes --enable-lora
docker run --name vllm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=" --env "VLLM_API_KEY=EMPTY" --env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" -p 8000:8000 --ipc=host vllm/vllm-openai:v0.19.0 TevunahAi/Granite-3.3-8B-Instruct-GPTQ --gpu-memory-utilization 0.87 --max_model_len 13632 --enable-auto-tool-choice --tool-call-parser granite --enable-lora