quarkus.container-image.group=epf
quarkus.container-image.name=epf-search
quarkus.kubernetes.name=epf-search
quarkus.http.port=9198
quarkus.jib.ports=9198
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9198
quarkus.kubernetes.ports."http".host-port=9198
quarkus.kubernetes.resources.requests.cpu=15m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.helm.name=epf-search
quarkus.kubernetes.env.vars.OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
quarkus.kubernetes.env.vars.OTEL_SERVICE_NAME=epf-search