quarkus.index-dependency.EPF-concurrent-utility-ext.group-id=openup
quarkus.index-dependency.EPF-concurrent-utility-ext.artifact-id=EPF-concurrent-utility-ext
quarkus.index-dependency.EPF-cache-utility.group-id=openup
quarkus.index-dependency.EPF-cache-utility.artifact-id=EPF-cache-utility
quarkus.kubernetes.env.vars.mp-messaging-connector-smallrye-kafka-security-protocol=SASL_PLAINTEXT
quarkus.kubernetes.env.vars.mp-messaging-connector-smallrye-kafka-sasl-mechanism=SCRAM-SHA-256
quarkus.kubernetes.env.vars.mp-messaging-connector-smallrye-kafka-sasl-jaas-config=org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="090323508";
quarkus.kubernetes.env.vars.mp-messaging-connector-smallrye-kafka-bootstrap-servers=kafka.default.svc.cluster.local:9092
mp.messaging.incoming.persistence.connector=smallrye-kafka
quarkus.container-image.group=epf
quarkus.container-image.name=epf-query
quarkus.kubernetes.name=epf-query
quarkus.http.port=9188
quarkus.jib.ports=9188
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9188
quarkus.kubernetes.ports."http".host-port=9188
quarkus.hibernate-orm.multitenant=DATABASE
quarkus.hibernate-orm.database.start-offline=true
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.packages=epf.delivery_processes.schema,epf.roles.schema,epf.tasks.schema,epf.work_products.schema,epf.schema.utility
epf.datasource.jdbc.url.format=jdbc:postgresql://localhost:6543/%s
epf.datasource.connection.pool.size=10
quarkus.kubernetes.env.vars.EPF_DATASOURCE_JDBC_URL_FORMAT=jdbc:postgresql://supavisor.default.svc.cluster.local:6543/%s
quarkus.kubernetes.env.vars.MP_JWT_VERIFY_PUBLICKEY_LOCATION=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev/protocol/openid-connect/certs
quarkus.kubernetes.env.vars.MP_JWT_VERIFY_ISSUER=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev
epf.messaging.url=ws://localhost:9183/messaging/
quarkus.kubernetes.env.vars.EPF_MESSAGING_URL=ws://epf-messaging.default.svc.cluster.local:9183/messaging/
quarkus.redis.hosts=redis://localhost:6379
quarkus.redis.password=090323508
quarkus.kubernetes.env.vars.QUARKUS_REDIS_HOSTS=redis://redis-master.default.svc.cluster.local:6379
quarkus.kubernetes.env.mapping.QUARKUS_REDIS_PASSWORD.from-secret=redis
quarkus.kubernetes.env.mapping.QUARKUS_REDIS_PASSWORD.with-key=redis-password
quarkus.helm.name=epf-query