DROP SCHEMA IF EXISTS OpenUP;
DROP SCHEMA IF EXISTS EPF_Tasks;
DROP SCHEMA IF EXISTS EPF_Work_Products;
DROP SCHEMA IF EXISTS EPF_Roles;
DROP SCHEMA IF EXISTS EPF_Delivery_Processes;
DROP SCHEMA IF EXISTS EPF_Net;

CREATE SCHEMA IF NOT EXISTS EPF_Delivery_Processes;
CREATE SCHEMA IF NOT EXISTS EPF_Roles;
CREATE SCHEMA IF NOT EXISTS EPF_Tasks;
CREATE SCHEMA IF NOT EXISTS EPF_Work_Products;
CREATE SCHEMA IF NOT EXISTS OpenUP;
CREATE SCHEMA IF NOT EXISTS EPF_Net;