quarkus.container-image.group=epf
quarkus.container-image.name=epf-registry
quarkus.kubernetes.name=epf-registry
quarkus.http.port=9182
quarkus.jib.ports=9182
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9182
quarkus.kubernetes.ports."http".host-port=9182
quarkus.kubernetes.env.vars.epf-schedule-url=http://openup:9080/schedule/schedule/
quarkus.kubernetes.env.vars.epf-script-url=http://openup:9080/script/script/
quarkus.kubernetes.env.vars.epf-file-url=http://epf-file:9194/file/
quarkus.kubernetes.env.vars.epf-mail-url=http://openup:9080/mail/mail/
quarkus.kubernetes.env.vars.epf-image-url=http://openup:9080/image/image/
quarkus.kubernetes.env.vars.epf-rules-url=http://openup:9080/rules/rules/
quarkus.kubernetes.env.vars.epf-planning-url=http://openup:9080/planning/planning/
quarkus.kubernetes.env.vars.epf-management-url=http://epf-management:9196/management/
quarkus.kubernetes.env.vars.epf-persistence-url=http://epf-persistence:9181/persistence/
quarkus.kubernetes.env.vars.epf-schema-url=http://epf-query:9181/schema/
quarkus.kubernetes.env.vars.epf-messaging-url=ws://epf-messaging:9183/messaging/
quarkus.kubernetes.env.vars.epf-config-url=http://epf-config:9184/config/
quarkus.kubernetes.env.vars.epf-net-url=http://epf-net:9186/net/
quarkus.kubernetes.env.vars.epf-cache-url=http://epf-cache:9187/cache/
quarkus.kubernetes.env.vars.epf-query-url=http://epf-query:9188/query/
quarkus.kubernetes.env.vars.epf-registry-url=http://epf-registry:9182/registry/
quarkus.kubernetes.env.vars.epf-workflow-url=http://epf-workflow:9189/workflow/
quarkus.kubernetes.env.vars.epf-workflow-management-url=http://epf-workflow-management:9191/workflow-management/
quarkus.kubernetes.env.vars.epf-event-url=http://epf-event:9192/event/
quarkus.kubernetes.env.vars.epf-concurrent-url=ws://epf-concurrent:9193/
quarkus.kubernetes.env.vars.epf-lang-url=http://epf-lang:9195/lang/
quarkus.kubernetes.env.vars.epf-net-http-port=9080
quarkus.kubernetes.resources.requests.cpu=25m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.helm.name=epf-registry