kcpBindPort = 7000
quicBindPort = 7002
vhostHTTPPort = 80
vhostHTTPSPort = 443
tcpmuxHTTPConnectPort = 1337
tcpmuxPassthrough = true
transport.tls.force = true
transport.tls.certFile = "/frp-tls/tls.crt"
transport.tls.keyFile = "/frp-tls/tls.key"
transport.tls.trustedCaFile = "/frp-tls/ca.crt"
webServer.port = 7500
log.level = "trace"
auth.method = "oidc"
auth.additionalScopes = ["NewWorkConns"]
auth.oidc.issuer = "https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev"
subDomainHost = "lvh.me"
sshTunnelGateway.bindPort = 2200
sshTunnelGateway.privateKeyFile = "/frp-ssh/ssh-privatekey"
sshTunnelGateway.authorizedKeysFile = "{{ .Envs.SSH_TUNNEL_GATEWAY_AUTHORIZED_KEYS_FILE }}"