quarkus.container-image.group=epf
quarkus.container-image.name=epf-management
quarkus.kubernetes.name=epf-management
quarkus.http.port=9196
quarkus.jib.ports=9196
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9196
quarkus.kubernetes.ports."http".host-port=9196
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".min-level=TRACE
#quarkus.kubernetes.resources.requests.cpu=50m
#quarkus.kubernetes.resources.requests.memory=128Mi
#quarkus.kubernetes.resources.limits.cpu=75m
#quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.kubernetes.env.vars.MP_JWT_VERIFY_PUBLICKEY_LOCATION=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev/protocol/openid-connect/certs
quarkus.kubernetes.env.vars.MP_JWT_VERIFY_ISSUER=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev
quarkus.helm.name=epf-management
quarkus.redis.hosts=redis://localhost:6379
quarkus.kubernetes.env.vars.QUARKUS_REDIS_HOSTS=redis://redis-master.default.svc.cluster.local:6379
quarkus.redis.password=090323508
quarkus.cache.redis.epf-management-organization.value-type=epf.management.schema.Organization
quarkus.cache.redis.epf-management-organization.expire-after-write=24h
quarkus.cache.redis.epf-management-organization.use-optimistic-locking=true
quarkus.rest-client.epf-management-auth.url=https://gateway.docker.internal/auth/realms/master/protocol/openid-connect
quarkus.rest-client.epf-management-admin.url=https://gateway.docker.internal/auth/admin/realms/EPF-dev
quarkus.rest-client.epf-persistence-management.url=http://localhost:4000/api
quarkus.kubernetes.env.vars.QUARKUS_REST_CLIENT_EPF_PERSISTENCE_MANAGEMENT_URL=http://supavisor.default.svc.cluster.local:4000/api
quarkus.kubernetes.env.vars.QUARKUS_REST_CLIENT_EPF_MANAGEMENT_AUTH_URL=https://keycloak.default.svc.cluster.local/auth/realms/master/protocol/openid-connect
quarkus.kubernetes.env.vars.QUARKUS_REST_CLIENT_EPF_MANAGEMENT_ADMIN_URL=https://keycloak.default.svc.cluster.local/auth/admin/realms/EPF-dev
quarkus.tls.tls-disabled.trust-all=true
quarkus.tls.tls-disabled.hostname-verification-algorithm=NONE
quarkus.rest-client.epf-management-auth.tls-configuration-name=tls-disabled
quarkus.rest-client.epf-management-admin.tls-configuration-name=tls-disabled
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.kubernetes.env.vars.QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql.default.svc.cluster.local:5432/postgres
quarkus.datasource.username=postgres
quarkus.datasource.password=090323508
quarkus.kubernetes.env.mapping.epf-management-persistence-secret.from-secret=supavisor
quarkus.kubernetes.env.mapping.epf-management-persistence-secret.with-key=API_JWT_SECRET
quarkus.vertx.max-event-loop-execute-time=60s