quarkus.container-image.group=epf
quarkus.container-image.name=epf-management
quarkus.kubernetes.name=epf-management
quarkus.http.port=9196
quarkus.jib.ports=9196
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9196
quarkus.kubernetes.ports."http".host-port=9196
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".min-level=TRACE
#quarkus.kubernetes.resources.requests.cpu=50m
#quarkus.kubernetes.resources.requests.memory=128Mi
#quarkus.kubernetes.resources.limits.cpu=75m
#quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.kubernetes.env.vars.MP_JWT_VERIFY_PUBLICKEY_LOCATION=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev/protocol/openid-connect/certs
quarkus.kubernetes.env.vars.MP_JWT_VERIFY_ISSUER=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev
quarkus.helm.name=epf-management
quarkus.cache.redis.epf_management_organization.value-type=epf.management.schema.Organization
quarkus.cache.redis.epf_management_organization.expire-after-write=24h
quarkus.cache.redis.epf_management_organization.use-optimistic-locking=true