quarkus.container-image.group=epf
quarkus.container-image.name=epf-management
quarkus.kubernetes.name=epf-management
quarkus.http.port=9196
quarkus.jib.ports=9196
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=9196
quarkus.kubernetes.ports."http".host-port=9196
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".min-level=TRACE
quarkus.kubernetes.resources.requests.cpu=25m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.kubernetes.env.vars.MP_JWT_VERIFY_PUBLICKEY_LOCATION=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev/protocol/openid-connect/certs
quarkus.kubernetes.env.vars.MP_JWT_VERIFY_ISSUER=https://chipmunk-capable-prawn.ngrok-free.app/auth/realms/EPF-dev
quarkus.kubernetes.env.vars.QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.helm.name=epf-management
quarkus.redis.hosts=redis://localhost:6379
quarkus.redis.password=090323508
quarkus.kubernetes.env.vars.QUARKUS_REDIS_HOSTS=redis://redis-master:6379
quarkus.kubernetes.env.mapping.QUARKUS_REDIS_PASSWORD.from-secret=redis
quarkus.kubernetes.env.mapping.QUARKUS_REDIS_PASSWORD.with-key=redis-password
quarkus.kubernetes.env.mapping.EPF_DATASOURCE_USER_DEFAULT.from-secret=odoo
quarkus.kubernetes.env.mapping.EPF_DATASOURCE_USER_DEFAULT.with-key=user
quarkus.kubernetes.env.mapping.EPF_DATASOURCE_PASSWORD_DEFAULT.from-secret=odoo
quarkus.kubernetes.env.mapping.EPF_DATASOURCE_PASSWORD_DEFAULT.with-key=password
quarkus.cache.redis.epf-management-organization.value-type=epf.management.schema.Organization
quarkus.cache.redis.epf-management-organization.expire-after-write=24h
quarkus.cache.redis.epf-management-organization.use-optimistic-locking=true
quarkus.rest-client.epf-management-auth.url=https://gateway.docker.internal/auth/realms/master/protocol/openid-connect
quarkus.rest-client.epf-management-admin.url=https://gateway.docker.internal/auth/admin/realms/EPF-dev
quarkus.rest-client.epf-persistence-management.url=http://localhost:4000/api
quarkus.kubernetes.env.vars.QUARKUS_REST_CLIENT_EPF_PERSISTENCE_MANAGEMENT_URL=http://supavisor:4000/api
quarkus.kubernetes.env.vars.QUARKUS_REST_CLIENT_EPF_MANAGEMENT_AUTH_URL=https://keycloak:8443/auth/realms/master/protocol/openid-connect
quarkus.kubernetes.env.vars.QUARKUS_REST_CLIENT_EPF_MANAGEMENT_ADMIN_URL=https://keycloak:8443/auth/admin/realms/EPF-dev
quarkus.tls.tls-disabled.trust-all=true
quarkus.tls.tls-disabled.hostname-verification-algorithm=NONE
quarkus.rest-client.epf-management-auth.tls-configuration-name=tls-disabled
quarkus.rest-client.epf-management-admin.tls-configuration-name=tls-disabled
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:6543/postgres
quarkus.datasource.username=postgres.postgres
quarkus.datasource.password=090323508
quarkus.kubernetes.env.vars.QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://supavisor:6543/postgres
quarkus.kubernetes.env.mapping.QUARKUS_DATASOURCE_PASSWORD.from-secret=postgresql
quarkus.kubernetes.env.mapping.QUARKUS_DATASOURCE_PASSWORD.with-key=postgres-password
quarkus.vertx.max-event-loop-execute-time=60s
quarkus.kubernetes.secret-volumes.epf-management-auth-client-secret.secret-name=keycloak-admin
quarkus.kubernetes.secret-volumes.epf-management-auth-client-secret.items.CLIENT_SECRET.path=epf.management.auth.client.secret
quarkus.kubernetes.mounts.epf-management-auth-client-secret.path=/epf/config/management
quarkus.kubernetes.secret-volumes.epf-management-persistence-secret.secret-name=supavisor
quarkus.kubernetes.secret-volumes.epf-management-persistence-secret.items.API_JWT_SECRET.path=epf.management.persistence.secret
quarkus.kubernetes.mounts.epf-management-persistence-secret.path=/epf/config/persistence