apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  config:
    featureGates:
    - HonorWaitForFirstConsumer
  imagePullPolicy: IfNotPresent
  infra:
    apiServerReplicas: 1
    deploymentReplicas: 1
    nodeSelector:
      kubernetes.io/os: linux
    uploadProxyReplicas: 1
  workload:
    nodeSelector:
      kubernetes.io/os: linux
