apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  config:
    featureGates:
    - HonorWaitForFirstConsumer
    podResourceRequirements:
      requests:
        cpu: "5m"
  imagePullPolicy: IfNotPresent
  infra:
    apiServerReplicas: 0
    deploymentReplicas: 0
    nodeSelector:
      kubernetes.io/os: linux
    uploadProxyReplicas: 0
  workload:
    nodeSelector:
      kubernetes.io/os: linux
