quarkus.container-image.group=epf
quarkus.container-image.name=epf-agent-webapp
quarkus.kubernetes.name=epf-agent-webapp
quarkus.http.port=3000
quarkus.jib.ports=3000
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.ports."http".container-port=3000
quarkus.kubernetes.ports."http".host-port=3000
quarkus.kubernetes.resources.requests.cpu=25m
quarkus.kubernetes.resources.requests.memory=128Mi
quarkus.kubernetes.resources.limits.cpu=150m
quarkus.kubernetes.resources.limits.memory=192Mi
quarkus.helm.name=epf-agent-webapp