quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.packages=epf.delivery_processes.schema,epf.roles.schema,epf.tasks.schema,epf.work_products.schema,epf.schema.utility
quarkus.arc.remove-unused-beans=framework