resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 1024Mi
    cpu: 500m
service:
  type: ClusterIP
persistence:
  size: 1Gi
auth:
  password: "090323508"
image:
  debug: true
