<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
       <groupId>epf</groupId>
       <artifactId>EPF-webapp-parent</artifactId>
       <version>1.0.0</version>
       <relativePath>../EPF-webapp-parent/pom.xml</relativePath>
    </parent>
    <artifactId>EPF-webapp-internal-v2</artifactId>
    <name>Eclipse Process Framework Web Application Internal</name>
    <packaging>jar</packaging>
    
    <dependencies>
    	<dependency>
		    <groupId>org.eclipse.microprofile.rest.client</groupId>
		    <artifactId>microprofile-rest-client-api</artifactId>
    	</dependency>
    	<dependency>
            <groupId>openup</groupId>
            <artifactId>EPF-management-schema</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>openup</groupId>
            <artifactId>EPF-naming</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>